In [1]:
# Importing the required libraries
import pandas as pd
from google.colab import files

# PRIVATE

In [2]:
priv_df = pd.read_csv("/content/2018 Private WAEC Data.csv", header=None)

In [3]:
# Viewing the DataFrame
priv_df.head(10)

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15
0,WEST AFRICAN EXAMINATIONS COUNCIL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,"RESULT STATISTICS FOR 5 CREDITS IN ENGLISH ,M...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,WASSCE PRIVATE CANDIDATES EXAMINATION 2018,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,STATE,TOTAL NUMBER SAT,NaN,NaN,5 CREDITS AND ABOVE INCLUDING ENGLISH LANGUAGE,NaN,NaN,5 CREDITS AND ABOVE INCLUDING MATHEMATICS,NaN,NaN,5 CREDITS & ABOVE INCLUDING MATHEMATICS & ENGL...,NaN,NaN,% of 5 CREDITS AND ABOVE INCLUDING MATHEMATICS...,NaN,NaN
4,NaN,MALE,FEMALE,TOTAL,MALE,FEMALE,TOTAL,MALE,FEMALE,TOTAL,MALE,FEMALE,TOTAL,MALE,FEMALE,TOTAL
5,ABIA,308,291,599,176,176,352,172,170,342,155,153,308,50.32,52.58,51.42
6,ABUJA,"1,184","1,240","2,424",131,179,310,96,79,175,78,70,148,6.59,5.65,6.11
7,ADAMAWA,91,56,147,6,4,10,8,4,12,4,1,5,4.40,1.79,3.40
8,AKWA IBOM,352,362,714,79,72,151,56,59,115,46,45,91,13.07,12.43,12.75
9,ANAMBRA,465,482,947,109,101,210,84,61,145,66,51,117,14.19,10.58,12.35

In [20]:
# Renaming the columns
priv_df.columns = [
    "state",
    "cands_male",
    "cands_female",
    "cands_total",
    "creds_5_eng_male",
    "creds_5_eng_female",
    "creds_5_eng_total",
    "creds_5_maths_male",
    "creds_5_maths_female",
    "creds_5_maths_total",
    "creds_5_eng_maths_male",
    "creds_5_eng_maths_female",
    "creds_5_eng_maths_total",
    "creds_5_eng_maths_male_pct",
    "creds_5_eng_maths_female_pct",
    "creds_5_eng_maths_total_pct"
]

In [6]:
# Creating a function to handle the column names
def state_handling(df):
  df["state"] = df["state"].astype("string").str.title()

  df["state"] = df["state"].replace(
      {"Abuja": "FCT"}
  )

  nigeria_column = df[df["state"] == "Nigeria"]
  df = df[df["state"] != "Nigeria"]

  df = df.sort_values("state")

  df = pd.concat([df, nigeria_column])

  df = df.reset_index(drop=True)

  return df

In [16]:
# Creating a function to handle the numerical columns
def numeric_handling(df, num_cols):
  for col in num_cols:
    df[col] = df[col].astype("string").str.replace(",", "", regex=False)
    df[col] = pd.to_numeric(df[col], errors="coerce").astype("Int64")

  return df

In [21]:
# Viewing the result
priv_df

,state,cands_male,cands_female,cands_total,creds_5_eng_male,creds_5_eng_female,creds_5_eng_total,creds_5_maths_male,creds_5_maths_female,creds_5_maths_total,creds_5_eng_maths_male,creds_5_eng_maths_female,creds_5_eng_maths_total,creds_5_eng_maths_male_pct,creds_5_eng_maths_female_pct,creds_5_eng_maths_total_pct
0,WEST AFRICAN EXAMINATIONS COUNCIL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,"RESULT STATISTICS FOR 5 CREDITS IN ENGLISH ,M...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,WASSCE PRIVATE CANDIDATES EXAMINATION 2018,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,STATE,TOTAL NUMBER SAT,NaN,NaN,5 CREDITS AND ABOVE INCLUDING ENGLISH LANGUAGE,NaN,NaN,5 CREDITS AND ABOVE INCLUDING MATHEMATICS,NaN,NaN,5 CREDITS & ABOVE INCLUDING MATHEMATICS & ENGL...,NaN,NaN,% of 5 CREDITS AND ABOVE INCLUDING MATHEMATICS...,NaN,NaN
4,NaN,MALE,FEMALE,TOTAL,MALE,FEMALE,TOTAL,MALE,FEMALE,TOTAL,MALE,FEMALE,TOTAL,MALE,FEMALE,TOTAL
5,ABIA,308,291,599,176,176,352,172,170,342,155,153,308,50.32,52.58,51.42
6,ABUJA,"1,184","1,240","2,424",131,179,310,96,79,175,78,70,148,6.59,5.65,6.11
7,ADAMAWA,91,56,147,6,4,10,8,4,12,4,1,5,4.40,1.79,3.40
8,AKWA IBOM,352,362,714,79,72,151,56,59,115,46,45,91,13.07,12.43,12.75
9,ANAMBRA,465,482,947,109,101,210,84,61,145,66,51,117,14.19,10.58,12.35
10,BAUCHI,38,23,61,11,3,14,6,2,8,6,2,8,15.79,8.70,13.11
11,BAYELSA,152,159,311,5,8,13,8,4,12,4,4,8,2.63,2.52,2.57
12,BENUE,231,139,370,21,7,28,16,6,22,7,5,12,3.03,3.60,3.24
13,BORNO,62,29,91,4,2,6,2,-,2,2,-,2,3.23,0.00,2.20
14,CROSS RIVER,337,286,623,55,24,79,26,13,39,21,8,29,6.23,2.80,4.65
15,DELTA,"1,272","1,272","2,544",384,335,719,317,299,616,234,193,427,18.40,15.17,16.78
16,EBONYI,88,85,173,32,18,50,11,3,14,6,3,9,6.82,3.53,5.20
17,EDO,664,632,"1,296",143,117,260,73,33,106,57,23,80,8.58,3.64,6.17
18,EKITI,242,233,475,38,34,72,25,16,41,18,15,33,7.44,6.44,6.95
19,ENUGU,844,868,"1,712",170,161,331,115,120,235,88,77,165,10.43,8.87,9.64
20,GOMBE,23,23,46,1,1,2,2,-,2,1,-,1,4.35,0.00,2.17
21,IMO,277,256,533,86,63,149,64,44,108,61,39,100,22.02,15.23,18.76
22,JIGAWA,18,2,20,3,-,3,3,-,3,3,-,3,16.67,0.00,15.00
23,KADUNA,426,430,856,104,101,205,84,69,153,68,55,123,15.96,12.79,14.37
24,KANO,742,454,"1,196",419,282,701,444,301,745,373,256,629,50.27,56.39,52.59
25,KATSINA,124,87,211,10,5,15,18,8,26,7,2,9,5.65,2.30,4.27
26,KEBBI,38,21,59,11,7,18,9,4,13,9,4,13,23.68,19.05,22.03
27,KOGI,414,366,780,56,57,113,46,49,95,39,44,83,9.42,12.02,10.64
28,KWARA,927,928,"1,855",245,265,510,204,159,363,159,132,291,17.15,14.22,15.69
29,LAGOS,"23,599","25,052","48,651","11,979","13,231","25,210","12,979","14,196","27,175","10,327","11,287","21,614",43.76,45.05,44.43
30,NASSARAWA,422,326,748,165,155,320,137,132,269,127,116,243,30.09,35.58,32.49
31,NIGER,664,566,"1,230",204,160,364,131,94,225,84,68,152,12.65,12.01,12.36
32,OGUN,"10,667","11,412","22,079","5,240","5,605","10,845","5,691","6,079","11,770","4,338","4,558","8,896",40.67,39.94,40.29
33,ONDO,558,508,"1,066",113,82,195,104,45,149,74,35,109,13.26,6.89,10.23
34,OSUN,"1,013","1,001","2,014",303,272,575,195,140,335,158,113,271,15.60,11.29,13.46
35,OYO,"4,478","4,568","9,046","1,232","1,275","2,507",901,661,"1,562",700,562,"1,262",15.63,12.30,13.95
36,PLATEAU,363,341,704,73,85,158,56,51,107,45,43,88,12.40,12.61,12.50
37,RIVERS,"3,197","2,990","6,187","1,317","1,276","2,593","1,231","1,191","2,422",953,875,"1,828",29.81,29.26,29.55
38,SOKOTO,69,36,105,17,12,29,13,10,23,13,10,23,18.84,27.78,21.90
39,TARABA,48,27,75,4,-,4,3,1,4,3,-,3,6.25,0.00,4.00
40,YOBE,5,1,6,1,-,1,1,-,1,1,-,1,20.00,0.00,16.67
41,ZAMFARA,15,9,24,-,-,-,-,-,-,-,-,-,0.00,0.00,0.00
42,NIGERIA,"54,417","55,561","109,978","22,947","24,175","47,122","23,331","24,103","47,434","18,335","18,849","37,184",33.69,33.92,33.81

In [22]:
# Dropping the irrelevant rows
priv_df = priv_df.drop(axis=0, index=[0, 1, 2, 3, 4]).reset_index(drop=True)

In [23]:
# Viewing the result
priv_df

,state,cands_male,cands_female,cands_total,creds_5_eng_male,creds_5_eng_female,creds_5_eng_total,creds_5_maths_male,creds_5_maths_female,creds_5_maths_total,creds_5_eng_maths_male,creds_5_eng_maths_female,creds_5_eng_maths_total,creds_5_eng_maths_male_pct,creds_5_eng_maths_female_pct,creds_5_eng_maths_total_pct
0,ABIA,308,291,599,176,176,352,172,170,342,155,153,308,50.32,52.58,51.42
1,ABUJA,"1,184","1,240","2,424",131,179,310,96,79,175,78,70,148,6.59,5.65,6.11
2,ADAMAWA,91,56,147,6,4,10,8,4,12,4,1,5,4.40,1.79,3.40
3,AKWA IBOM,352,362,714,79,72,151,56,59,115,46,45,91,13.07,12.43,12.75
4,ANAMBRA,465,482,947,109,101,210,84,61,145,66,51,117,14.19,10.58,12.35
5,BAUCHI,38,23,61,11,3,14,6,2,8,6,2,8,15.79,8.70,13.11
6,BAYELSA,152,159,311,5,8,13,8,4,12,4,4,8,2.63,2.52,2.57
7,BENUE,231,139,370,21,7,28,16,6,22,7,5,12,3.03,3.60,3.24
8,BORNO,62,29,91,4,2,6,2,-,2,2,-,2,3.23,0.00,2.20
9,CROSS RIVER,337,286,623,55,24,79,26,13,39,21,8,29,6.23,2.80,4.65
10,DELTA,"1,272","1,272","2,544",384,335,719,317,299,616,234,193,427,18.40,15.17,16.78
11,EBONYI,88,85,173,32,18,50,11,3,14,6,3,9,6.82,3.53,5.20
12,EDO,664,632,"1,296",143,117,260,73,33,106,57,23,80,8.58,3.64,6.17
13,EKITI,242,233,475,38,34,72,25,16,41,18,15,33,7.44,6.44,6.95
14,ENUGU,844,868,"1,712",170,161,331,115,120,235,88,77,165,10.43,8.87,9.64
15,GOMBE,23,23,46,1,1,2,2,-,2,1,-,1,4.35,0.00,2.17
16,IMO,277,256,533,86,63,149,64,44,108,61,39,100,22.02,15.23,18.76
17,JIGAWA,18,2,20,3,-,3,3,-,3,3,-,3,16.67,0.00,15.00
18,KADUNA,426,430,856,104,101,205,84,69,153,68,55,123,15.96,12.79,14.37
19,KANO,742,454,"1,196",419,282,701,444,301,745,373,256,629,50.27,56.39,52.59
20,KATSINA,124,87,211,10,5,15,18,8,26,7,2,9,5.65,2.30,4.27
21,KEBBI,38,21,59,11,7,18,9,4,13,9,4,13,23.68,19.05,22.03
22,KOGI,414,366,780,56,57,113,46,49,95,39,44,83,9.42,12.02,10.64
23,KWARA,927,928,"1,855",245,265,510,204,159,363,159,132,291,17.15,14.22,15.69
24,LAGOS,"23,599","25,052","48,651","11,979","13,231","25,210","12,979","14,196","27,175","10,327","11,287","21,614",43.76,45.05,44.43
25,NASSARAWA,422,326,748,165,155,320,137,132,269,127,116,243,30.09,35.58,32.49
26,NIGER,664,566,"1,230",204,160,364,131,94,225,84,68,152,12.65,12.01,12.36
27,OGUN,"10,667","11,412","22,079","5,240","5,605","10,845","5,691","6,079","11,770","4,338","4,558","8,896",40.67,39.94,40.29
28,ONDO,558,508,"1,066",113,82,195,104,45,149,74,35,109,13.26,6.89,10.23
29,OSUN,"1,013","1,001","2,014",303,272,575,195,140,335,158,113,271,15.60,11.29,13.46
30,OYO,"4,478","4,568","9,046","1,232","1,275","2,507",901,661,"1,562",700,562,"1,262",15.63,12.30,13.95
31,PLATEAU,363,341,704,73,85,158,56,51,107,45,43,88,12.40,12.61,12.50
32,RIVERS,"3,197","2,990","6,187","1,317","1,276","2,593","1,231","1,191","2,422",953,875,"1,828",29.81,29.26,29.55
33,SOKOTO,69,36,105,17,12,29,13,10,23,13,10,23,18.84,27.78,21.90
34,TARABA,48,27,75,4,-,4,3,1,4,3,-,3,6.25,0.00,4.00
35,YOBE,5,1,6,1,-,1,1,-,1,1,-,1,20.00,0.00,16.67
36,ZAMFARA,15,9,24,-,-,-,-,-,-,-,-,-,0.00,0.00,0.00
37,NIGERIA,"54,417","55,561","109,978","22,947","24,175","47,122","23,331","24,103","47,434","18,335","18,849","37,184",33.69,33.92,33.81

In [24]:
priv_df = state_handling(priv_df)

In [25]:
# Viewing the result
priv_df

,state,cands_male,cands_female,cands_total,creds_5_eng_male,creds_5_eng_female,creds_5_eng_total,creds_5_maths_male,creds_5_maths_female,creds_5_maths_total,creds_5_eng_maths_male,creds_5_eng_maths_female,creds_5_eng_maths_total,creds_5_eng_maths_male_pct,creds_5_eng_maths_female_pct,creds_5_eng_maths_total_pct
0,Abia,308,291,599,176,176,352,172,170,342,155,153,308,50.32,52.58,51.42
1,Adamawa,91,56,147,6,4,10,8,4,12,4,1,5,4.40,1.79,3.40
2,Akwa Ibom,352,362,714,79,72,151,56,59,115,46,45,91,13.07,12.43,12.75
3,Anambra,465,482,947,109,101,210,84,61,145,66,51,117,14.19,10.58,12.35
4,Bauchi,38,23,61,11,3,14,6,2,8,6,2,8,15.79,8.70,13.11
5,Bayelsa,152,159,311,5,8,13,8,4,12,4,4,8,2.63,2.52,2.57
6,Benue,231,139,370,21,7,28,16,6,22,7,5,12,3.03,3.60,3.24
7,Borno,62,29,91,4,2,6,2,-,2,2,-,2,3.23,0.00,2.20
8,Cross River,337,286,623,55,24,79,26,13,39,21,8,29,6.23,2.80,4.65
9,Delta,"1,272","1,272","2,544",384,335,719,317,299,616,234,193,427,18.40,15.17,16.78
10,Ebonyi,88,85,173,32,18,50,11,3,14,6,3,9,6.82,3.53,5.20
11,Edo,664,632,"1,296",143,117,260,73,33,106,57,23,80,8.58,3.64,6.17
12,Ekiti,242,233,475,38,34,72,25,16,41,18,15,33,7.44,6.44,6.95
13,Enugu,844,868,"1,712",170,161,331,115,120,235,88,77,165,10.43,8.87,9.64
14,FCT,"1,184","1,240","2,424",131,179,310,96,79,175,78,70,148,6.59,5.65,6.11
15,Gombe,23,23,46,1,1,2,2,-,2,1,-,1,4.35,0.00,2.17
16,Imo,277,256,533,86,63,149,64,44,108,61,39,100,22.02,15.23,18.76
17,Jigawa,18,2,20,3,-,3,3,-,3,3,-,3,16.67,0.00,15.00
18,Kaduna,426,430,856,104,101,205,84,69,153,68,55,123,15.96,12.79,14.37
19,Kano,742,454,"1,196",419,282,701,444,301,745,373,256,629,50.27,56.39,52.59
20,Katsina,124,87,211,10,5,15,18,8,26,7,2,9,5.65,2.30,4.27
21,Kebbi,38,21,59,11,7,18,9,4,13,9,4,13,23.68,19.05,22.03
22,Kogi,414,366,780,56,57,113,46,49,95,39,44,83,9.42,12.02,10.64
23,Kwara,927,928,"1,855",245,265,510,204,159,363,159,132,291,17.15,14.22,15.69
24,Lagos,"23,599","25,052","48,651","11,979","13,231","25,210","12,979","14,196","27,175","10,327","11,287","21,614",43.76,45.05,44.43
25,Nassarawa,422,326,748,165,155,320,137,132,269,127,116,243,30.09,35.58,32.49
26,Niger,664,566,"1,230",204,160,364,131,94,225,84,68,152,12.65,12.01,12.36
27,Ogun,"10,667","11,412","22,079","5,240","5,605","10,845","5,691","6,079","11,770","4,338","4,558","8,896",40.67,39.94,40.29
28,Ondo,558,508,"1,066",113,82,195,104,45,149,74,35,109,13.26,6.89,10.23
29,Osun,"1,013","1,001","2,014",303,272,575,195,140,335,158,113,271,15.60,11.29,13.46
30,Oyo,"4,478","4,568","9,046","1,232","1,275","2,507",901,661,"1,562",700,562,"1,262",15.63,12.30,13.95
31,Plateau,363,341,704,73,85,158,56,51,107,45,43,88,12.40,12.61,12.50
32,Rivers,"3,197","2,990","6,187","1,317","1,276","2,593","1,231","1,191","2,422",953,875,"1,828",29.81,29.26,29.55
33,Sokoto,69,36,105,17,12,29,13,10,23,13,10,23,18.84,27.78,21.90
34,Taraba,48,27,75,4,-,4,3,1,4,3,-,3,6.25,0.00,4.00
35,Yobe,5,1,6,1,-,1,1,-,1,1,-,1,20.00,0.00,16.67
36,Zamfara,15,9,24,-,-,-,-,-,-,-,-,-,0.00,0.00,0.00
37,Nigeria,"54,417","55,561","109,978","22,947","24,175","47,122","23,331","24,103","47,434","18,335","18,849","37,184",33.69,33.92,33.81

In [26]:
# Handling the numerical columns
num_cols = [
    "cands_male",
    "cands_female",
    "cands_total",
    "creds_5_eng_male",
    "creds_5_eng_female",
    "creds_5_eng_total",
    "creds_5_maths_male",
    "creds_5_maths_female",
    "creds_5_maths_total",
    "creds_5_eng_maths_male",
    "creds_5_eng_maths_female",
    "creds_5_eng_maths_total",
    "creds_5_eng_maths_male_pct",
    "creds_5_eng_maths_female_pct",
    "creds_5_eng_maths_total_pct"
]
priv_df = numeric_handling(priv_df, num_cols)

In [27]:
# Viewing the result
priv_df

,state,cands_male,cands_female,cands_total,creds_5_eng_male,creds_5_eng_female,creds_5_eng_total,creds_5_maths_male,creds_5_maths_female,creds_5_maths_total,creds_5_eng_maths_male,creds_5_eng_maths_female,creds_5_eng_maths_total,creds_5_eng_maths_male_pct,creds_5_eng_maths_female_pct,creds_5_eng_maths_total_pct
0,Abia,308,291,599,176,176,352,172,170,342,155,153,308,50,52,51
1,Adamawa,91,56,147,6,4,10,8,4,12,4,1,5,4,1,3
2,Akwa Ibom,352,362,714,79,72,151,56,59,115,46,45,91,13,12,12
3,Anambra,465,482,947,109,101,210,84,61,145,66,51,117,14,10,12
4,Bauchi,38,23,61,11,3,14,6,2,8,6,2,8,15,8,13
5,Bayelsa,152,159,311,5,8,13,8,4,12,4,4,8,2,2,2
6,Benue,231,139,370,21,7,28,16,6,22,7,5,12,3,3,3
7,Borno,62,29,91,4,2,6,2,<NA>,2,2,<NA>,2,3,0,2
8,Cross River,337,286,623,55,24,79,26,13,39,21,8,29,6,2,4
9,Delta,1272,1272,2544,384,335,719,317,299,616,234,193,427,18,15,16
10,Ebonyi,88,85,173,32,18,50,11,3,14,6,3,9,6,3,5
11,Edo,664,632,1296,143,117,260,73,33,106,57,23,80,8,3,6
12,Ekiti,242,233,475,38,34,72,25,16,41,18,15,33,7,6,6
13,Enugu,844,868,1712,170,161,331,115,120,235,88,77,165,10,8,9
14,FCT,1184,1240,2424,131,179,310,96,79,175,78,70,148,6,5,6
15,Gombe,23,23,46,1,1,2,2,<NA>,2,1,<NA>,1,4,0,2
16,Imo,277,256,533,86,63,149,64,44,108,61,39,100,22,15,18
17,Jigawa,18,2,20,3,<NA>,3,3,<NA>,3,3,<NA>,3,16,0,15
18,Kaduna,426,430,856,104,101,205,84,69,153,68,55,123,15,12,14
19,Kano,742,454,1196,419,282,701,444,301,745,373,256,629,50,56,52
20,Katsina,124,87,211,10,5,15,18,8,26,7,2,9,5,2,4
21,Kebbi,38,21,59,11,7,18,9,4,13,9,4,13,23,19,22
22,Kogi,414,366,780,56,57,113,46,49,95,39,44,83,9,12,10
23,Kwara,927,928,1855,245,265,510,204,159,363,159,132,291,17,14,15
24,Lagos,23599,25052,48651,11979,13231,25210,12979,14196,27175,10327,11287,21614,43,45,44
25,Nassarawa,422,326,748,165,155,320,137,132,269,127,116,243,30,35,32
26,Niger,664,566,1230,204,160,364,131,94,225,84,68,152,12,12,12
27,Ogun,10667,11412,22079,5240,5605,10845,5691,6079,11770,4338,4558,8896,40,39,40
28,Ondo,558,508,1066,113,82,195,104,45,149,74,35,109,13,6,10
29,Osun,1013,1001,2014,303,272,575,195,140,335,158,113,271,15,11,13
30,Oyo,4478,4568,9046,1232,1275,2507,901,661,1562,700,562,1262,15,12,13
31,Plateau,363,341,704,73,85,158,56,51,107,45,43,88,12,12,12
32,Rivers,3197,2990,6187,1317,1276,2593,1231,1191,2422,953,875,1828,29,29,29
33,Sokoto,69,36,105,17,12,29,13,10,23,13,10,23,18,27,21
34,Taraba,48,27,75,4,<NA>,4,3,1,4,3,<NA>,3,6,0,4
35,Yobe,5,1,6,1,<NA>,1,1,<NA>,1,1,<NA>,1,20,0,16
36,Zamfara,15,9,24,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,0,0,0
37,Nigeria,54417,55561,109978,22947,24175,47122,23331,24103,47434,18335,18849,37184,33,33,33

In [28]:
# Saving the DataFrame
file_name = "Cleaned 2018 Private WAEC Data.csv"
priv_df.to_csv(file_name, index=False)
files.download(file_name)

# PUBLIC

In [5]:
pub_df = pd.read_csv("")

In [8]:
# Viewing the DataFrame
pub_df.head(10)

,WEST AFRICAN EXAMINATIONS COUNCIL,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15
0,"RESULT STATISTICS FOR 5 CREDITS IN ENGLISH ,M...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,WASSCE CANDIDATES EXAMINATION 2018,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,STATE,TOTAL NUMBER SAT,NaN,NaN,5 CREDITS AND ABOVE INCLUDING ENGLISH LANGUAGE,NaN,NaN,5 CREDITS AND ABOVE INCLUDING MATHEMATICS,NaN,NaN,5 CREDITS & ABOVE INCLUDING MATHEMATICS & ENGL...,NaN,NaN,% of 5 CREDITS AND ABOVE INCLUDING MATHEMATICS...,NaN,NaN
3,NaN,MALE,FEMALE,TOTAL,MALE,FEMALE,TOTAL,MALE,FEMALE,TOTAL,MALE,FEMALE,TOTAL,MALE,FEMALE,TOTAL
4,ABIA,"22,502","24,966","47,468","19,711","22,056","41,767","20,239","22,426","42,665","18,484","20,572","39,056",82.14,82.40,82.28
5,ABUJA,"10,711","12,911","23,622","7,061","8,615","15,676","6,927","7,537","14,464","5,851","6,459","12,310",54.63,50.03,52.11
6,ADAMAWA,"12,664","9,373","22,037","4,952","3,527","8,479","7,623","5,632","13,255","4,521","3,090","7,611",35.70,32.97,34.54
7,AKWA IBOM,"26,651","28,246","54,897","14,875","16,796","31,671","19,265","21,486","40,751","13,901","15,682","29,583",52.16,55.52,53.89
8,ANAMBRA,"19,942","24,608","44,550","12,619","15,794","28,413","14,755","17,701","32,456","10,308","12,589","22,897",51.69,51.16,51.40
9,BAUCHI,"27,015","15,172","42,187","5,596","4,380","9,976","9,080","6,427","15,507","4,887","3,650","8,537",18.09,24.06,20.24

In [9]:
# Renaming the columns
pub_df.columns = [
    "state",
    "cands_male",
    "cands_female",
    "cands_total",
    "creds_5_eng_male",
    "creds_5_eng_female",
    "creds_5_eng_total",
    "creds_5_maths_male",
    "creds_5_maths_female",
    "creds_5_maths_total",
    "creds_5_eng_maths_male",
    "creds_5_eng_maths_female",
    "creds_5_eng_maths_total",
    "creds_5_eng_maths_male_pct",
    "creds_5_eng_maths_female_pct",
    "creds_5_eng_maths_total_pct"
]

In [10]:
# Viewing the result
pub_df

,state,cands_male,cands_female,cands_total,creds_5_eng_male,creds_5_eng_female,creds_5_eng_total,creds_5_maths_male,creds_5_maths_female,creds_5_maths_total,creds_5_eng_maths_male,creds_5_eng_maths_female,creds_5_eng_maths_total,creds_5_eng_maths_male_pct,creds_5_eng_maths_female_pct,creds_5_eng_maths_total_pct
0,"RESULT STATISTICS FOR 5 CREDITS IN ENGLISH ,M...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,WASSCE CANDIDATES EXAMINATION 2018,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,STATE,TOTAL NUMBER SAT,NaN,NaN,5 CREDITS AND ABOVE INCLUDING ENGLISH LANGUAGE,NaN,NaN,5 CREDITS AND ABOVE INCLUDING MATHEMATICS,NaN,NaN,5 CREDITS & ABOVE INCLUDING MATHEMATICS & ENGL...,NaN,NaN,% of 5 CREDITS AND ABOVE INCLUDING MATHEMATICS...,NaN,NaN
3,NaN,MALE,FEMALE,TOTAL,MALE,FEMALE,TOTAL,MALE,FEMALE,TOTAL,MALE,FEMALE,TOTAL,MALE,FEMALE,TOTAL
4,ABIA,"22,502","24,966","47,468","19,711","22,056","41,767","20,239","22,426","42,665","18,484","20,572","39,056",82.14,82.40,82.28
5,ABUJA,"10,711","12,911","23,622","7,061","8,615","15,676","6,927","7,537","14,464","5,851","6,459","12,310",54.63,50.03,52.11
6,ADAMAWA,"12,664","9,373","22,037","4,952","3,527","8,479","7,623","5,632","13,255","4,521","3,090","7,611",35.70,32.97,34.54
7,AKWA IBOM,"26,651","28,246","54,897","14,875","16,796","31,671","19,265","21,486","40,751","13,901","15,682","29,583",52.16,55.52,53.89
8,ANAMBRA,"19,942","24,608","44,550","12,619","15,794","28,413","14,755","17,701","32,456","10,308","12,589","22,897",51.69,51.16,51.40
9,BAUCHI,"27,015","15,172","42,187","5,596","4,380","9,976","9,080","6,427","15,507","4,887","3,650","8,537",18.09,24.06,20.24
10,BAYELSA,"10,448","9,980","20,428","7,192","6,918","14,110","7,864","7,524","15,388","6,075","5,820","11,895",58.15,58.32,58.23
11,BENUE,"24,957","19,422","44,379","14,858","11,595","26,453","16,757","12,791","29,548","11,810","9,059","20,869",47.32,46.64,47.02
12,BORNO,"20,266","14,120","34,386","4,320","3,376","7,696","9,226","7,583","16,809","3,958","3,139","7,097",19.53,22.23,20.64
13,CROSS RIVER,"18,377","18,024","36,401","10,935","11,029","21,964","12,754","13,071","25,825","9,701","9,872","19,573",52.79,54.77,53.77
14,DELTA,"25,715","27,831","53,546","13,963","16,008","29,971","17,459","19,583","37,042","12,965","14,789","27,754",50.42,53.14,51.83
15,EBONYI,"12,260","12,710","24,970","8,735","8,932","17,667","9,802","10,222","20,024","7,684","7,816","15,500",62.68,61.49,62.07
16,EDO,"29,055","30,776","59,831","19,165","21,657","40,822","23,016","25,328","48,344","17,455","19,879","37,334",60.08,64.59,62.40
17,EKITI,"9,491","9,566","19,057","5,576","5,904","11,480","8,082","8,350","16,432","5,284","5,543","10,827",55.67,57.94,56.81
18,ENUGU,"18,606","22,722","41,328","12,544","15,231","27,775","15,100","18,083","33,183","11,652","13,831","25,483",62.62,60.87,61.66
19,GOMBE,"9,557","6,771","16,328","1,451","1,493","2,944","3,606","3,103","6,709","1,367","1,380","2,747",14.30,20.38,16.82
20,IMO,"21,851","23,698","45,549","17,051","19,320","36,371","19,119","21,200","40,319","15,959","18,088","34,047",73.04,76.33,74.75
21,JIGAWA,"15,515","6,909","22,424","1,587","1,049","2,636","4,061","1,918","5,979","1,225",888,"2,113",7.90,12.85,9.42
22,KADUNA,"44,289","37,023","81,312","20,456","18,314","38,770","28,320","24,890","53,210","17,388","15,728","33,116",39.26,42.48,40.73
23,KANO,"16,248","13,755","30,003","9,101","8,418","17,519","11,385","10,726","22,111","8,463","7,932","16,395",52.09,57.67,54.64
24,KATSINA,"15,216","8,700","23,916","5,197","3,114","8,311","9,397","5,827","15,224","4,388","2,800","7,188",28.84,32.18,30.06
25,KEBBI,"20,238","9,884","30,122","8,224","4,914","13,138","11,834","6,687","18,521","7,551","4,616","12,167",37.31,46.70,40.39
26,KOGI,"16,208","14,171","30,379","6,574","6,129","12,703","8,707","8,121","16,828","5,293","4,977","10,270",32.66,35.12,33.81
27,KWARA,"17,949","17,431","35,380","9,707","10,099","19,806","12,801","12,767","25,568","8,560","8,861","17,421",47.69,50.83,49.24
28,LAGOS,"76,607","85,459","162,066","50,402","58,021","108,423","56,692","62,649","119,341","46,239","52,172","98,411",60.36,61.05,60.72
29,NASSARAWA,"26,248","21,125","47,373","13,290","11,229","24,519","18,303","15,217","33,520","11,439","9,692","21,131",43.58,45.88,44.61
30,NIGER,"29,740","21,850","51,590","7,802","6,672","14,474","13,790","11,377","25,167","6,954","6,009","12,963",23.38,27.50,25.13
31,OGUN,"44,403","47,351","91,754","24,928","27,737","52,665","28,220","30,901","59,121","22,523","24,909","47,432",50.72,52.61,51.69
32,ONDO,"19,444","19,913","39,357","10,924","12,234","23,158","12,534","13,446","25,980","9,769","10,781","20,550",50.24,54.14,52.21
33,OSUN,"18,098","18,073","36,171","8,497","9,029","17,526","10,590","10,902","21,492","7,224","7,552","14,776",39.92,41.79,40.85
34,OYO,"31,245","34,095","65,340","13,471","15,337","28,808","18,625","20,652","39,277","11,688","13,054","24,742",37.41,38.29,37.87
35,PLATEAU,"20,438","18,670","39,108","6,039","5,570","11,609","11,102","10,446","21,548","5,190","4,724","9,914",25.39,25.30,25.35
36,RIVERS,"31,062","33,943","65,005","25,710","28,656","54,366","27,307","29,951","57,258","23,995","26,592","50,587",77.25,78.34,77.82
37,SOKOTO,"17,395","8,689","26,084","6,028","3,435","9,463","9,836","5,761","15,597","5,584","3,293","8,877",32.10,37.90,34.03
38,YOBE,"11,819","5,079","16,898","2,411","1,249","3,660","4,280","2,568","6,848","1,657","1,017","2,674",14.02,20.02,15.82
39,ZAMFARA,"20,146","8,335","28,481","2,575","1,359","3,934","8,589","4,868","13,457","2,249","1,155","3,404",11.16,13.86,11.95
40,OFFSHORE,96,132,228,36,58,94,29,35,64,17,21,38,17.71,15.91,16.67
41,NIGERIA,"822,941","748,595","1,571,536","419,699","429,370","849,069","534,871","523,183","1,058,054","374,871","381,855","756,726",45.55,51.01,48.15
42,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
43,NaN,NaN,NaN,NaN,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [11]:
# Dropping the irrelevant rows
pub_df = pub_df.drop(axis=0, index=[0, 1, 2, 3, 40, 42, 43]).reset_index(drop=True)

In [12]:
# Viewing the result
pub_df.head(10)
# Taraba unavailable

,state,cands_male,cands_female,cands_total,creds_5_eng_male,creds_5_eng_female,creds_5_eng_total,creds_5_maths_male,creds_5_maths_female,creds_5_maths_total,creds_5_eng_maths_male,creds_5_eng_maths_female,creds_5_eng_maths_total,creds_5_eng_maths_male_pct,creds_5_eng_maths_female_pct,creds_5_eng_maths_total_pct
0,ABIA,"22,502","24,966","47,468","19,711","22,056","41,767","20,239","22,426","42,665","18,484","20,572","39,056",82.14,82.40,82.28
1,ABUJA,"10,711","12,911","23,622","7,061","8,615","15,676","6,927","7,537","14,464","5,851","6,459","12,310",54.63,50.03,52.11
2,ADAMAWA,"12,664","9,373","22,037","4,952","3,527","8,479","7,623","5,632","13,255","4,521","3,090","7,611",35.70,32.97,34.54
3,AKWA IBOM,"26,651","28,246","54,897","14,875","16,796","31,671","19,265","21,486","40,751","13,901","15,682","29,583",52.16,55.52,53.89
4,ANAMBRA,"19,942","24,608","44,550","12,619","15,794","28,413","14,755","17,701","32,456","10,308","12,589","22,897",51.69,51.16,51.40
5,BAUCHI,"27,015","15,172","42,187","5,596","4,380","9,976","9,080","6,427","15,507","4,887","3,650","8,537",18.09,24.06,20.24
6,BAYELSA,"10,448","9,980","20,428","7,192","6,918","14,110","7,864","7,524","15,388","6,075","5,820","11,895",58.15,58.32,58.23
7,BENUE,"24,957","19,422","44,379","14,858","11,595","26,453","16,757","12,791","29,548","11,810","9,059","20,869",47.32,46.64,47.02
8,BORNO,"20,266","14,120","34,386","4,320","3,376","7,696","9,226","7,583","16,809","3,958","3,139","7,097",19.53,22.23,20.64
9,CROSS RIVER,"18,377","18,024","36,401","10,935","11,029","21,964","12,754","13,071","25,825","9,701","9,872","19,573",52.79,54.77,53.77

In [13]:
pub_df = state_handling(pub_df)

In [14]:
pub_df

,state,cands_male,cands_female,cands_total,creds_5_eng_male,creds_5_eng_female,creds_5_eng_total,creds_5_maths_male,creds_5_maths_female,creds_5_maths_total,creds_5_eng_maths_male,creds_5_eng_maths_female,creds_5_eng_maths_total,creds_5_eng_maths_male_pct,creds_5_eng_maths_female_pct,creds_5_eng_maths_total_pct
0,Abia,"22,502","24,966","47,468","19,711","22,056","41,767","20,239","22,426","42,665","18,484","20,572","39,056",82.14,82.40,82.28
1,Adamawa,"12,664","9,373","22,037","4,952","3,527","8,479","7,623","5,632","13,255","4,521","3,090","7,611",35.70,32.97,34.54
2,Akwa Ibom,"26,651","28,246","54,897","14,875","16,796","31,671","19,265","21,486","40,751","13,901","15,682","29,583",52.16,55.52,53.89
3,Anambra,"19,942","24,608","44,550","12,619","15,794","28,413","14,755","17,701","32,456","10,308","12,589","22,897",51.69,51.16,51.40
4,Bauchi,"27,015","15,172","42,187","5,596","4,380","9,976","9,080","6,427","15,507","4,887","3,650","8,537",18.09,24.06,20.24
5,Bayelsa,"10,448","9,980","20,428","7,192","6,918","14,110","7,864","7,524","15,388","6,075","5,820","11,895",58.15,58.32,58.23
6,Benue,"24,957","19,422","44,379","14,858","11,595","26,453","16,757","12,791","29,548","11,810","9,059","20,869",47.32,46.64,47.02
7,Borno,"20,266","14,120","34,386","4,320","3,376","7,696","9,226","7,583","16,809","3,958","3,139","7,097",19.53,22.23,20.64
8,Cross River,"18,377","18,024","36,401","10,935","11,029","21,964","12,754","13,071","25,825","9,701","9,872","19,573",52.79,54.77,53.77
9,Delta,"25,715","27,831","53,546","13,963","16,008","29,971","17,459","19,583","37,042","12,965","14,789","27,754",50.42,53.14,51.83
10,Ebonyi,"12,260","12,710","24,970","8,735","8,932","17,667","9,802","10,222","20,024","7,684","7,816","15,500",62.68,61.49,62.07
11,Edo,"29,055","30,776","59,831","19,165","21,657","40,822","23,016","25,328","48,344","17,455","19,879","37,334",60.08,64.59,62.40
12,Ekiti,"9,491","9,566","19,057","5,576","5,904","11,480","8,082","8,350","16,432","5,284","5,543","10,827",55.67,57.94,56.81
13,Enugu,"18,606","22,722","41,328","12,544","15,231","27,775","15,100","18,083","33,183","11,652","13,831","25,483",62.62,60.87,61.66
14,FCT,"10,711","12,911","23,622","7,061","8,615","15,676","6,927","7,537","14,464","5,851","6,459","12,310",54.63,50.03,52.11
15,Gombe,"9,557","6,771","16,328","1,451","1,493","2,944","3,606","3,103","6,709","1,367","1,380","2,747",14.30,20.38,16.82
16,Imo,"21,851","23,698","45,549","17,051","19,320","36,371","19,119","21,200","40,319","15,959","18,088","34,047",73.04,76.33,74.75
17,Jigawa,"15,515","6,909","22,424","1,587","1,049","2,636","4,061","1,918","5,979","1,225",888,"2,113",7.90,12.85,9.42
18,Kaduna,"44,289","37,023","81,312","20,456","18,314","38,770","28,320","24,890","53,210","17,388","15,728","33,116",39.26,42.48,40.73
19,Kano,"16,248","13,755","30,003","9,101","8,418","17,519","11,385","10,726","22,111","8,463","7,932","16,395",52.09,57.67,54.64
20,Katsina,"15,216","8,700","23,916","5,197","3,114","8,311","9,397","5,827","15,224","4,388","2,800","7,188",28.84,32.18,30.06
21,Kebbi,"20,238","9,884","30,122","8,224","4,914","13,138","11,834","6,687","18,521","7,551","4,616","12,167",37.31,46.70,40.39
22,Kogi,"16,208","14,171","30,379","6,574","6,129","12,703","8,707","8,121","16,828","5,293","4,977","10,270",32.66,35.12,33.81
23,Kwara,"17,949","17,431","35,380","9,707","10,099","19,806","12,801","12,767","25,568","8,560","8,861","17,421",47.69,50.83,49.24
24,Lagos,"76,607","85,459","162,066","50,402","58,021","108,423","56,692","62,649","119,341","46,239","52,172","98,411",60.36,61.05,60.72
25,Nassarawa,"26,248","21,125","47,373","13,290","11,229","24,519","18,303","15,217","33,520","11,439","9,692","21,131",43.58,45.88,44.61
26,Niger,"29,740","21,850","51,590","7,802","6,672","14,474","13,790","11,377","25,167","6,954","6,009","12,963",23.38,27.50,25.13
27,Ogun,"44,403","47,351","91,754","24,928","27,737","52,665","28,220","30,901","59,121","22,523","24,909","47,432",50.72,52.61,51.69
28,Ondo,"19,444","19,913","39,357","10,924","12,234","23,158","12,534","13,446","25,980","9,769","10,781","20,550",50.24,54.14,52.21
29,Osun,"18,098","18,073","36,171","8,497","9,029","17,526","10,590","10,902","21,492","7,224","7,552","14,776",39.92,41.79,40.85
30,Oyo,"31,245","34,095","65,340","13,471","15,337","28,808","18,625","20,652","39,277","11,688","13,054","24,742",37.41,38.29,37.87
31,Plateau,"20,438","18,670","39,108","6,039","5,570","11,609","11,102","10,446","21,548","5,190","4,724","9,914",25.39,25.30,25.35
32,Rivers,"31,062","33,943","65,005","25,710","28,656","54,366","27,307","29,951","57,258","23,995","26,592","50,587",77.25,78.34,77.82
33,Sokoto,"17,395","8,689","26,084","6,028","3,435","9,463","9,836","5,761","15,597","5,584","3,293","8,877",32.10,37.90,34.03
34,Yobe,"11,819","5,079","16,898","2,411","1,249","3,660","4,280","2,568","6,848","1,657","1,017","2,674",14.02,20.02,15.82
35,Zamfara,"20,146","8,335","28,481","2,575","1,359","3,934","8,589","4,868","13,457","2,249","1,155","3,404",11.16,13.86,11.95
36,Nigeria,"822,941","748,595","1,571,536","419,699","429,370","849,069","534,871","523,183","1,058,054","374,871","381,855","756,726",45.55,51.01,48.15

In [17]:
# Handling the numeric columns
num_cols = [
    "cands_male",
    "cands_female",
    "cands_total",
    "creds_5_eng_male",
    "creds_5_eng_female",
    "creds_5_eng_total",
    "creds_5_maths_male",
    "creds_5_maths_female",
    "creds_5_maths_total",
    "creds_5_eng_maths_male",
    "creds_5_eng_maths_female",
    "creds_5_eng_maths_total",
    "creds_5_eng_maths_male_pct",
    "creds_5_eng_maths_female_pct",
    "creds_5_eng_maths_total_pct"
]

pub_df = numeric_handling(pub_df, num_cols)

In [18]:
# Viewing the result
pub_df

,state,cands_male,cands_female,cands_total,creds_5_eng_male,creds_5_eng_female,creds_5_eng_total,creds_5_maths_male,creds_5_maths_female,creds_5_maths_total,creds_5_eng_maths_male,creds_5_eng_maths_female,creds_5_eng_maths_total,creds_5_eng_maths_male_pct,creds_5_eng_maths_female_pct,creds_5_eng_maths_total_pct
0,Abia,22502,24966,47468,19711,22056,41767,20239,22426,42665,18484,20572,39056,82,82,82
1,Adamawa,12664,9373,22037,4952,3527,8479,7623,5632,13255,4521,3090,7611,35,32,34
2,Akwa Ibom,26651,28246,54897,14875,16796,31671,19265,21486,40751,13901,15682,29583,52,55,53
3,Anambra,19942,24608,44550,12619,15794,28413,14755,17701,32456,10308,12589,22897,51,51,51
4,Bauchi,27015,15172,42187,5596,4380,9976,9080,6427,15507,4887,3650,8537,18,24,20
5,Bayelsa,10448,9980,20428,7192,6918,14110,7864,7524,15388,6075,5820,11895,58,58,58
6,Benue,24957,19422,44379,14858,11595,26453,16757,12791,29548,11810,9059,20869,47,46,47
7,Borno,20266,14120,34386,4320,3376,7696,9226,7583,16809,3958,3139,7097,19,22,20
8,Cross River,18377,18024,36401,10935,11029,21964,12754,13071,25825,9701,9872,19573,52,54,53
9,Delta,25715,27831,53546,13963,16008,29971,17459,19583,37042,12965,14789,27754,50,53,51
10,Ebonyi,12260,12710,24970,8735,8932,17667,9802,10222,20024,7684,7816,15500,62,61,62
11,Edo,29055,30776,59831,19165,21657,40822,23016,25328,48344,17455,19879,37334,60,64,62
12,Ekiti,9491,9566,19057,5576,5904,11480,8082,8350,16432,5284,5543,10827,55,57,56
13,Enugu,18606,22722,41328,12544,15231,27775,15100,18083,33183,11652,13831,25483,62,60,61
14,FCT,10711,12911,23622,7061,8615,15676,6927,7537,14464,5851,6459,12310,54,50,52
15,Gombe,9557,6771,16328,1451,1493,2944,3606,3103,6709,1367,1380,2747,14,20,16
16,Imo,21851,23698,45549,17051,19320,36371,19119,21200,40319,15959,18088,34047,73,76,74
17,Jigawa,15515,6909,22424,1587,1049,2636,4061,1918,5979,1225,888,2113,7,12,9
18,Kaduna,44289,37023,81312,20456,18314,38770,28320,24890,53210,17388,15728,33116,39,42,40
19,Kano,16248,13755,30003,9101,8418,17519,11385,10726,22111,8463,7932,16395,52,57,54
20,Katsina,15216,8700,23916,5197,3114,8311,9397,5827,15224,4388,2800,7188,28,32,30
21,Kebbi,20238,9884,30122,8224,4914,13138,11834,6687,18521,7551,4616,12167,37,46,40
22,Kogi,16208,14171,30379,6574,6129,12703,8707,8121,16828,5293,4977,10270,32,35,33
23,Kwara,17949,17431,35380,9707,10099,19806,12801,12767,25568,8560,8861,17421,47,50,49
24,Lagos,76607,85459,162066,50402,58021,108423,56692,62649,119341,46239,52172,98411,60,61,60
25,Nassarawa,26248,21125,47373,13290,11229,24519,18303,15217,33520,11439,9692,21131,43,45,44
26,Niger,29740,21850,51590,7802,6672,14474,13790,11377,25167,6954,6009,12963,23,27,25
27,Ogun,44403,47351,91754,24928,27737,52665,28220,30901,59121,22523,24909,47432,50,52,51
28,Ondo,19444,19913,39357,10924,12234,23158,12534,13446,25980,9769,10781,20550,50,54,52
29,Osun,18098,18073,36171,8497,9029,17526,10590,10902,21492,7224,7552,14776,39,41,40
30,Oyo,31245,34095,65340,13471,15337,28808,18625,20652,39277,11688,13054,24742,37,38,37
31,Plateau,20438,18670,39108,6039,5570,11609,11102,10446,21548,5190,4724,9914,25,25,25
32,Rivers,31062,33943,65005,25710,28656,54366,27307,29951,57258,23995,26592,50587,77,78,77
33,Sokoto,17395,8689,26084,6028,3435,9463,9836,5761,15597,5584,3293,8877,32,37,34
34,Yobe,11819,5079,16898,2411,1249,3660,4280,2568,6848,1657,1017,2674,14,20,15
35,Zamfara,20146,8335,28481,2575,1359,3934,8589,4868,13457,2249,1155,3404,11,13,11
36,Nigeria,822941,748595,1571536,419699,429370,849069,534871,523183,1058054,374871,381855,756726,45,51,48

In [19]:
# Saving the result
file_name = "Cleaned 2018 Public WAEC Data.csv"

pub_df.to_csv(file_name, index=False)
files.download(file_name)