In [1]:
# Importing the required libraries
import pandas as pd
from google.colab import files

# 2017 PRIVATE WAEC DATA

In [2]:
# # Loading the DataFrame
# priv_waec_16 = pd.read_csv("/content/2016 Private WAEC Data.csv")

In [3]:
# # Viewing the DataFrame
# priv_waec_16.head()

In [4]:
# # Renaming the columns
# priv_waec_16.columns = [
#     "state",
#     "waec_male",
#     "waec_female",
#     "waec_total",
#     "credits_5_eng_male",
#     "credits_5_eng_female",
#     "credits_5_eng_total",
#     "credits_5_maths_male",
#     "credits_5_maths_female",
#     "credits_5_maths_total",
#     "credits_5_eng_male",
#     "credits_5_eng_female",
#     "credits_5_eng_total",
#     "credits_5_maths_eng_male",
#     "credits_5_maths_eng_female",
#     "credits_5_maths_eng_total",
#     ""
# ]

# 2019 WAEC DATA

In [5]:
# # Loading the DataFrame
# waec_19 = pd.read_csv("/content/2019 WAEC Data.csv")

In [6]:
# # Viewing the DataFrame
# waec_19.head(10)

In [7]:
# # Renaming the columns
# waec_19.columns = [
#     "priv_s/no",
#     "priv_state",
#     "priv_cands_male",
#     "priv_cands_female",
#     "priv_cands_total",
#     "missing_values_1",
#     "missing_values_2",

# ]

In [8]:
# df = pd.read_excel("/content/WAEC_STATISTICS_2019-2021.xlsx")

In [9]:
# df.head(10)

# 2021 WAEC DATA

In [10]:
raw_21 = pd.read_csv("/content/2021 WAEC Data.csv", header=None)

In [11]:
# Viewing the number of rows and columns in the raw DataFrame
raw_21.shape

(45, 67)

## Defining a function to clean numeric columns

In [12]:
def clean_numeric(df, num_cols):
  for col in num_cols:
    df[col] = (
        df[col]
        .astype("string")
        .str.replace(",", "", regex=False)
    )

    df[col] = pd.to_numeric(
        df[col], errors="coerce"
    )

  return df

# Defining a function to clean state names

In [13]:
def clean_states(df):
  df["state"] = df["state"].astype("string").str.title()

  # Replacing Abuja with FCT
  df["state"] = df["state"].replace({
      "Abuja": "FCT"
  })

  # Removing Offshore
  df = df[
      ~df["state"].isin(["Offshore"])
  ]

  # Removing rows where state is missing
  df = df[df["state"].notna()]

  # Separating out the "Total" row so it isn't sorted alphabetically
  total_row = df[df["state"] == "Total"]
  df = df[df["state"] != "Total"]

  # Sorting the remaining states alphabetically
  df = df.sort_values("state")

  # Appending "Total" back as the last row
  df = pd.concat([df, total_row])

  # Resetting index
  df = df.reset_index(drop=True)

  return df

## Creating the Private Students DataFrame

In [14]:
priv_stud_21 = raw_21.iloc[:, 1:5].copy()

In [15]:
priv_stud_21.columns = [
    "state",
    "private_cand_male",
    "private_cand_female",
    "private_cand_total"
]

In [16]:
priv_stud_21 = clean_states(priv_stud_21)

In [17]:
priv_stud_21 = clean_numeric(
    priv_stud_21, [
      "private_cand_male",
      "private_cand_female",
      "private_cand_total"
    ]
)

In [18]:
# Viewing the result
priv_stud_21

          state  private_cand_male  private_cand_female  private_cand_total
0          Abia              16589                18260               34849
1       Adamawa               2822                 2537                5359
2     Akwa Ibom               7814                 8124               15938
3       Anambra              12157                14782               26939
4        Bauchi               3994                 3181                7175
5       Bayelsa               1365                 1561                2926
6         Benue              15909                13521               29430
7         Borno               5413                 4658               10071
8   Cross River               8555                 9037               17592
9         Delta              11396                12955               24351
10       Ebonyi               4149                 4551                8700
11          Edo              16155                18578               34733
12        Ekiti               3936                 4206                8142
13        Enugu               8313                 9562               17875
14          FCT               6187                 6841               13028
15        Gombe               1666                 1440                3106
16          Imo               8801                 9953               18754
17       Jigawa                462                  380                 842
18       Kaduna              17519                16837               34356
19         Kano               6912                 6871               13783
20      Katsina               2305                 2042                4347
21        Kebbi                974                  779                1753
22         Kogi               4601                 4487                9088
23        Kwara               6623                 6549               13172
24        Lagos              56207                63192              119399
25    Nassarawa               9264                 9983               19247
26        Niger               6662                 7197               13859
27         Ogun              35511                39142               74653
28         Ondo               9356                 9424               18780
29         Osun               9296                10193               19489
30          Oyo              18503                20200               38703
31      Plateau               9233                 8973               18206
32       Rivers              13610                15223               28833
33       Sokoto               1284                 1090                2374
34        State               <NA>                 <NA>                <NA>
35       Taraba               2677                 2151                4828
36         Yobe               1611                 2007                3618
37      Zamfara               1832                 1364                3196
38        Total             349745               371921              721666

# Creating the Private Students English credit DataFrame

In [19]:
priv_eng_21 = raw_21.iloc[:, 8:15].copy()

In [20]:
priv_eng_21.head(10)

,8,9,10,11,12,13,14
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,STATE,TOTAL NUMBER SAT,NaN,NaN,5 CREDITS & ABOVE INCLUDING ENGLISH\n\n,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,MALE,FEMALE,TOTAL,MALE,FEMALE,TOTAL
6,ABIA,"16,589","18,260","34,849","15,909","17,517","33,426"
7,ABUJA,"6,187","6,841","13,028","5,622","6,250","11,872"
8,ADAMAWA,"2,822","2,537","5,359","2,565","2,361","4,926"
9,AKWA IBOM,"7,814","8,124","15,938","7,295","7,666","14,961"

In [21]:
priv_eng_21.columns = [
    "state",
    "priv_cand_male",
    "priv_cand_female",
    "priv_cand_total",
    "priv_cred_5_eng_male",
    "priv_cred_5_eng_female",
    "priv_cred_5_eng_total"
]

In [22]:
priv_eng_21 = clean_states(priv_eng_21)

In [23]:
priv_eng_21 = clean_numeric(
    priv_eng_21, [
      "priv_cand_male",
      "priv_cand_female",
      "priv_cand_total",
      "priv_cred_5_eng_male",
      "priv_cred_5_eng_female",
      "priv_cred_5_eng_total"
    ]
)

In [24]:
priv_eng_21

,state,priv_cand_male,priv_cand_female,priv_cand_total,priv_cred_5_eng_male,priv_cred_5_eng_female,priv_cred_5_eng_total
0,Abia,16589,18260,34849,15909,17517,33426
1,Adamawa,2822,2537,5359,2565,2361,4926
2,Akwa Ibom,7814,8124,15938,7295,7666,14961
3,Anambra,12157,14782,26939,11475,13957,25432
4,Bauchi,3994,3181,7175,3172,2662,5834
5,Bayelsa,1365,1561,2926,1165,1360,2525
6,Benue,15909,13521,29430,14746,12650,27396
7,Borno,5413,4658,10071,4249,3878,8127
8,Cross River,8555,9037,17592,7783,8441,16224
9,Delta,11396,12955,24351,10474,12151,22625
10,Ebonyi,4149,4551,8700,3957,4323,8280
11,Edo,16155,18578,34733,15028,17377,32405
12,Ekiti,3936,4206,8142,3774,4034,7808
13,Enugu,8313,9562,17875,7927,9148,17075
14,FCT,6187,6841,13028,5622,6250,11872
15,Gombe,1666,1440,3106,1533,1285,2818
16,Imo,8801,9953,18754,8297,9452,17749
17,Jigawa,462,380,842,389,329,718
18,Kaduna,17519,16837,34356,15879,15536,31415
19,Kano,6912,6871,13783,6321,6466,12787
20,Katsina,2305,2042,4347,1717,1647,3364
21,Kebbi,974,779,1753,937,762,1699
22,Kogi,4601,4487,9088,4131,4099,8230
23,Kwara,6623,6549,13172,5506,5550,11056
24,Lagos,56207,63192,119399,51255,58480,109735
25,Nassarawa,9264,9983,19247,8543,9276,17819
26,Niger,6662,7197,13859,5887,6394,12281
27,Ogun,35511,39142,74653,33691,37411,71102
28,Ondo,9356,9424,18780,8464,8714,17178
29,Osun,9296,10193,19489,6433,7336,13769
30,Oyo,18503,20200,38703,15525,17102,32627
31,Plateau,9233,8973,18206,8074,7927,16001
32,Rivers,13610,15223,28833,12734,14395,27129
33,Sokoto,1284,1090,2374,1260,1072,2332
34,State,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
35,Taraba,2677,2151,4828,2374,1941,4315
36,Yobe,1611,2007,3618,1237,1602,2839
37,Zamfara,1832,1364,3196,1010,898,1908
38,Total,349745,371921,721666,316393,341522,657915

In [25]:
priv_eng_21

,state,priv_cand_male,priv_cand_female,priv_cand_total,priv_cred_5_eng_male,priv_cred_5_eng_female,priv_cred_5_eng_total
0,Abia,16589,18260,34849,15909,17517,33426
1,Adamawa,2822,2537,5359,2565,2361,4926
2,Akwa Ibom,7814,8124,15938,7295,7666,14961
3,Anambra,12157,14782,26939,11475,13957,25432
4,Bauchi,3994,3181,7175,3172,2662,5834
5,Bayelsa,1365,1561,2926,1165,1360,2525
6,Benue,15909,13521,29430,14746,12650,27396
7,Borno,5413,4658,10071,4249,3878,8127
8,Cross River,8555,9037,17592,7783,8441,16224
9,Delta,11396,12955,24351,10474,12151,22625
10,Ebonyi,4149,4551,8700,3957,4323,8280
11,Edo,16155,18578,34733,15028,17377,32405
12,Ekiti,3936,4206,8142,3774,4034,7808
13,Enugu,8313,9562,17875,7927,9148,17075
14,FCT,6187,6841,13028,5622,6250,11872
15,Gombe,1666,1440,3106,1533,1285,2818
16,Imo,8801,9953,18754,8297,9452,17749
17,Jigawa,462,380,842,389,329,718
18,Kaduna,17519,16837,34356,15879,15536,31415
19,Kano,6912,6871,13783,6321,6466,12787
20,Katsina,2305,2042,4347,1717,1647,3364
21,Kebbi,974,779,1753,937,762,1699
22,Kogi,4601,4487,9088,4131,4099,8230
23,Kwara,6623,6549,13172,5506,5550,11056
24,Lagos,56207,63192,119399,51255,58480,109735
25,Nassarawa,9264,9983,19247,8543,9276,17819
26,Niger,6662,7197,13859,5887,6394,12281
27,Ogun,35511,39142,74653,33691,37411,71102
28,Ondo,9356,9424,18780,8464,8714,17178
29,Osun,9296,10193,19489,6433,7336,13769
30,Oyo,18503,20200,38703,15525,17102,32627
31,Plateau,9233,8973,18206,8074,7927,16001
32,Rivers,13610,15223,28833,12734,14395,27129
33,Sokoto,1284,1090,2374,1260,1072,2332
34,State,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
35,Taraba,2677,2151,4828,2374,1941,4315
36,Yobe,1611,2007,3618,1237,1602,2839
37,Zamfara,1832,1364,3196,1010,898,1908
38,Total,349745,371921,721666,316393,341522,657915

## PRIVATE MATHS

In [26]:
priv_maths_21 = raw_21.iloc[:, [8, 9, 10, 11, 15, 16, 17]].copy()

In [27]:
priv_maths_21.columns = [
    "state",
    "priv_cand_male",
    "priv_cand_female",
    "priv_cand_total",
    "priv_cred_5_maths_male",
    "priv_cred_5_maths_female",
    "priv_cred_5_maths_total"
]

In [28]:
priv_maths_21.head(10)

,state,priv_cand_male,priv_cand_female,priv_cand_total,priv_cred_5_maths_male,priv_cred_5_maths_female,priv_cred_5_maths_total
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,STATE,TOTAL NUMBER SAT,NaN,NaN,5 CREDITS & ABOVE INCLUDING MATHEMATICS\n\n,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,MALE,FEMALE,TOTAL,MALE,FEMALE,TOTAL
6,ABIA,"16,589","18,260","34,849","13,580","14,931","28,511"
7,ABUJA,"6,187","6,841","13,028","5,358","5,866","11,224"
8,ADAMAWA,"2,822","2,537","5,359","2,599","2,322","4,921"
9,AKWA IBOM,"7,814","8,124","15,938","7,440","7,756","15,196"

In [29]:
priv_maths_21 = clean_states(priv_maths_21)

In [30]:
priv_maths_21 = clean_numeric(
    priv_maths_21, [
      "priv_cand_male",
      "priv_cand_female",
      "priv_cand_total",
      "priv_cred_5_maths_male",
      "priv_cred_5_maths_female",
      "priv_cred_5_maths_total"
    ]
)

In [31]:
priv_maths_21

,state,priv_cand_male,priv_cand_female,priv_cand_total,priv_cred_5_maths_male,priv_cred_5_maths_female,priv_cred_5_maths_total
0,Abia,16589,18260,34849,13580,14931,28511
1,Adamawa,2822,2537,5359,2599,2322,4921
2,Akwa Ibom,7814,8124,15938,7440,7756,15196
3,Anambra,12157,14782,26939,11572,14091,25663
4,Bauchi,3994,3181,7175,3295,2740,6035
5,Bayelsa,1365,1561,2926,1155,1317,2472
6,Benue,15909,13521,29430,15036,12850,27886
7,Borno,5413,4658,10071,4612,4123,8735
8,Cross River,8555,9037,17592,7952,8574,16526
9,Delta,11396,12955,24351,11031,12575,23606
10,Ebonyi,4149,4551,8700,3774,4166,7940
11,Edo,16155,18578,34733,15544,17958,33502
12,Ekiti,3936,4206,8142,2820,3028,5848
13,Enugu,8313,9562,17875,7721,8785,16506
14,FCT,6187,6841,13028,5358,5866,11224
15,Gombe,1666,1440,3106,1575,1344,2919
16,Imo,8801,9953,18754,7392,8300,15692
17,Jigawa,462,380,842,407,337,744
18,Kaduna,17519,16837,34356,15924,15377,31301
19,Kano,6912,6871,13783,6606,6673,13279
20,Katsina,2305,2042,4347,1697,1618,3315
21,Kebbi,974,779,1753,965,773,1738
22,Kogi,4601,4487,9088,4322,4229,8551
23,Kwara,6623,6549,13172,5088,5120,10208
24,Lagos,56207,63192,119399,51129,57656,108785
25,Nassarawa,9264,9983,19247,8593,9307,17900
26,Niger,6662,7197,13859,5946,6404,12350
27,Ogun,35511,39142,74653,33961,37508,71469
28,Ondo,9356,9424,18780,8488,8592,17080
29,Osun,9296,10193,19489,7036,7816,14852
30,Oyo,18503,20200,38703,16087,17620,33707
31,Plateau,9233,8973,18206,8320,8032,16352
32,Rivers,13610,15223,28833,12871,14364,27235
33,Sokoto,1284,1090,2374,1259,1062,2321
34,State,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
35,Taraba,2677,2151,4828,2506,2030,4536
36,Yobe,1611,2007,3618,1449,1856,3305
37,Zamfara,1832,1364,3196,929,813,1742
38,Total,349745,371921,721666,316088,337970,654058

## PRIVATE ENGLISH AND MATHS

In [32]:
priv_eng_maths_21 = raw_21.iloc[:, 21:29].copy()

In [33]:
priv_eng_maths_21.columns = [
    "state",
    "priv_cand_male",
    "priv_cand_female",
    "priv_cand_total",
    "priv_cred_5_eng_maths_male",
    "priv_cred_5_eng_maths_female",
    "priv_cred_5_eng_maths_total",
    "priv_cred_5_eng_maths_pct"
]

In [34]:
priv_eng_maths_21 = clean_states(priv_eng_maths_21)

In [35]:
priv_eng_maths_21 = clean_numeric(
    priv_eng_maths_21, [
      "priv_cand_male",
      "priv_cand_female",
      "priv_cand_total",
      "priv_cred_5_eng_maths_male",
      "priv_cred_5_eng_maths_female",
      "priv_cred_5_eng_maths_total",
      "priv_cred_5_eng_maths_pct"
    ]
)

In [36]:
priv_eng_maths_21

,state,priv_cand_male,priv_cand_female,priv_cand_total,priv_cred_5_eng_maths_male,priv_cred_5_eng_maths_female,priv_cred_5_eng_maths_total,priv_cred_5_eng_maths_pct
0,Abia,16589,18260,34849,13230,14486,27716,79.53
1,Adamawa,2822,2537,5359,2504,2254,4758,88.78
2,Akwa Ibom,7814,8124,15938,7176,7520,14696,92.2
3,Anambra,12157,14782,26939,11287,13724,25011,92.84
4,Bauchi,3994,3181,7175,3036,2560,5596,77.99
5,Bayelsa,1365,1561,2926,1118,1272,2390,81.68
6,Benue,15909,13521,29430,14480,12413,26893,91.37
7,Borno,5413,4658,10071,4091,3715,7806,77.5
8,Cross River,8555,9037,17592,7575,8242,15817,89.91
9,Delta,11396,12955,24351,10417,12047,22464,92.25
10,Ebonyi,4149,4551,8700,3699,4060,7759,89.18
11,Edo,16155,18578,34733,14848,17183,32031,92.22
12,Ekiti,3936,4206,8142,2759,2984,5743,70.53
13,Enugu,8313,9562,17875,7610,8692,16302,91.2
14,FCT,6187,6841,13028,5225,5726,10951,84.05
15,Gombe,1666,1440,3106,1505,1259,2764,88.98
16,Imo,8801,9953,18754,7212,8111,15323,81.7
17,Jigawa,462,380,842,361,308,669,79.45
18,Kaduna,17519,16837,34356,15100,14636,29736,86.55
19,Kano,6912,6871,13783,6251,6402,12653,91.8
20,Katsina,2305,2042,4347,1575,1522,3097,71.24
21,Kebbi,974,779,1753,935,761,1696,96.74
22,Kogi,4601,4487,9088,4070,4021,8091,89.02
23,Kwara,6623,6549,13172,4698,4714,9412,71.45
24,Lagos,56207,63192,119399,49019,55633,104652,87.64
25,Nassarawa,9264,9983,19247,8228,8931,17159,89.15
26,Niger,6662,7197,13859,5690,6134,11824,85.31
27,Ogun,35511,39142,74653,32955,36516,69471,93.05
28,Ondo,9356,9424,18780,8070,8242,16312,86.85
29,Osun,9296,10193,19489,6081,6780,12861,65.99
30,Oyo,18503,20200,38703,14750,16187,30937,79.93
31,Plateau,9233,8973,18206,7775,7561,15336,84.23
32,Rivers,13610,15223,28833,12320,13843,26163,90.73
33,Sokoto,1284,1090,2374,1251,1057,2308,97.21
34,State,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
35,Taraba,2677,2151,4828,2360,1930,4290,88.85
36,Yobe,1611,2007,3618,1165,1512,2677,73.99
37,Zamfara,1832,1364,3196,580,573,1153,36.08
38,Total,349745,371921,721666,301047,323565,624612,86.55

## PUBLIC SCHOOL CANDIDATES

In [37]:
pub_cands_21 = raw_21.iloc[:, 63:67].copy()

In [38]:
pub_cands_21.columns = [
    "state",
    "pub_cands_male",
    "pub_cands_female",
    "pub_cands_total"
]

In [39]:
pub_cands_21 = clean_states(pub_cands_21)

In [40]:
pub_cands_21 = clean_numeric(
    pub_cands_21, [
        "pub_cands_male",
        "pub_cands_female",
        "pub_cands_total"
    ]
)

In [41]:
pub_cands_21

          state  pub_cands_male  pub_cands_female  pub_cands_total
0          Abia            4293              5078             9371
1       Adamawa           24677             17967            42644
2     Akwa Ibom           17101             18721            35822
3       Anambra            8160             10809            18969
4        Bauchi            7420              4848            12268
5       Bayelsa            6462              6667            13129
6         Benue            6020              4841            10861
7         Borno           13282             10185            23467
8   Cross River            8160              7970            16130
9         Delta           16226             18564            34790
10       Ebonyi            7111              7769            14880
11          Edo           12049             13645            25694
12        Ekiti            7221              7149            14370
13        Enugu            9818             12241            22059
14          FCT            6862              8731            15593
15        Gombe            6531              5437            11968
16          Imo           13458             14146            27604
17       Jigawa            3720              1815             5535
18       Kaduna           18699             15558            34257
19         Kano            6089              6014            12103
20      Katsina            8136              5838            13974
21        Kebbi           18557             10667            29224
22         Kogi           10574              9121            19695
23        Kwara            8241              8129            16370
24        Lagos           25856             29939            55795
25    Nassarawa           13595             11304            24899
26        Niger           16666             12712            29378
27         Ogun           21293             22558            43851
28         Ondo           11734             12227            23961
29         Osun            6097              6346            12443
30          Oyo           27040             28017            55057
31      Plateau            6441              5461            11902
32       Rivers           25506             26502            52008
33       Sokoto            1536               618             2154
34        State            <NA>              <NA>             <NA>
35       Taraba            5823              4414            10237
36         Yobe           10193              3972            14165
37      Zamfara           14249              7610            21859
38        Total          434896            403590           838486

## PUBLIC ENGLISH

In [42]:
pub_eng_21 = raw_21.iloc[:, 32:39].copy()

In [43]:
pub_eng_21.columns = [
  "state",
  "pub_cands_male",
  "pub_cands_female",
  "pub_cands_total",
  "pub_creds_5_eng_male",
  "pub_creds_5_eng_female",
  "pub_creds_5_eng_total"
]

In [44]:
pub_eng_21 = clean_states(pub_eng_21)

In [45]:
pub_eng_21 = clean_numeric(
    pub_eng_21, [
      "pub_cands_male",
      "pub_cands_female",
      "pub_cands_total",
      "pub_creds_5_eng_male",
      "pub_creds_5_eng_female",
      "pub_creds_5_eng_total"
    ]
)

In [46]:
pub_eng_21

,state,pub_cands_male,pub_cands_female,pub_cands_total,pub_creds_5_eng_male,pub_creds_5_eng_female,pub_creds_5_eng_total
0,Abia,4293,5078,9371,4026,4802,8828
1,Adamawa,24677,17967,42644,17133,12864,29997
2,Akwa Ibom,17101,18721,35822,14576,16394,30970
3,Anambra,8160,10809,18969,7649,9971,17620
4,Bauchi,7420,4848,12268,5047,3668,8715
5,Bayelsa,6462,6667,13129,5657,5799,11456
6,Benue,6020,4841,10861,5664,4582,10246
7,Borno,13282,10185,23467,8708,7574,16282
8,Cross River,8160,7970,16130,7457,7477,14934
9,Delta,16226,18564,34790,14417,16694,31111
10,Ebonyi,7111,7769,14880,6513,7275,13788
11,Edo,12049,13645,25694,11215,12933,24148
12,Ekiti,7221,7149,14370,6405,6613,13018
13,Enugu,9818,12241,22059,9404,11804,21208
14,FCT,6862,8731,15593,5893,7386,13279
15,Gombe,6531,5437,11968,4839,4394,9233
16,Imo,13458,14146,27604,12723,13523,26246
17,Jigawa,3720,1815,5535,2834,1278,4112
18,Kaduna,18699,15558,34257,15297,13005,28302
19,Kano,6089,6014,12103,5041,4922,9963
20,Katsina,8136,5838,13974,4412,3320,7732
21,Kebbi,18557,10667,29224,14267,8707,22974
22,Kogi,10574,9121,19695,8742,7765,16507
23,Kwara,8241,8129,16370,4827,4962,9789
24,Lagos,25856,29939,55795,20137,24120,44257
25,Nassarawa,13595,11304,24899,11780,9990,21770
26,Niger,16666,12712,29378,12110,9350,21460
27,Ogun,21293,22558,43851,11826,13065,24891
28,Ondo,11734,12227,23961,9044,9763,18807
29,Osun,6097,6346,12443,2030,2440,4470
30,Oyo,27040,28017,55057,15102,16587,31689
31,Plateau,6441,5461,11902,5316,4568,9884
32,Rivers,25506,26502,52008,23265,24262,47527
33,Sokoto,1536,618,2154,1206,592,1798
34,State,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
35,Statistics On Performance Of Public Schools In...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
36,Taraba,5823,4414,10237,4996,3884,8880
37,Wassce For School Candidates (Sc) 2021,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
38,West African Examinations Council,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
39,Yobe,10193,3972,14165,5507,2743,8250
40,Zamfara,14249,7610,21859,1616,1371,2987
41,Total,434896,403590,838486,326681,320447,647128

In [47]:
# Removing the rows with missing values
pub_eng_21 = pub_eng_21.dropna(axis=0, how="any").reset_index(drop=True)

In [48]:
pub_eng_21

,state,pub_cands_male,pub_cands_female,pub_cands_total,pub_creds_5_eng_male,pub_creds_5_eng_female,pub_creds_5_eng_total
0,Abia,4293,5078,9371,4026,4802,8828
1,Adamawa,24677,17967,42644,17133,12864,29997
2,Akwa Ibom,17101,18721,35822,14576,16394,30970
3,Anambra,8160,10809,18969,7649,9971,17620
4,Bauchi,7420,4848,12268,5047,3668,8715
5,Bayelsa,6462,6667,13129,5657,5799,11456
6,Benue,6020,4841,10861,5664,4582,10246
7,Borno,13282,10185,23467,8708,7574,16282
8,Cross River,8160,7970,16130,7457,7477,14934
9,Delta,16226,18564,34790,14417,16694,31111
10,Ebonyi,7111,7769,14880,6513,7275,13788
11,Edo,12049,13645,25694,11215,12933,24148
12,Ekiti,7221,7149,14370,6405,6613,13018
13,Enugu,9818,12241,22059,9404,11804,21208
14,FCT,6862,8731,15593,5893,7386,13279
15,Gombe,6531,5437,11968,4839,4394,9233
16,Imo,13458,14146,27604,12723,13523,26246
17,Jigawa,3720,1815,5535,2834,1278,4112
18,Kaduna,18699,15558,34257,15297,13005,28302
19,Kano,6089,6014,12103,5041,4922,9963
20,Katsina,8136,5838,13974,4412,3320,7732
21,Kebbi,18557,10667,29224,14267,8707,22974
22,Kogi,10574,9121,19695,8742,7765,16507
23,Kwara,8241,8129,16370,4827,4962,9789
24,Lagos,25856,29939,55795,20137,24120,44257
25,Nassarawa,13595,11304,24899,11780,9990,21770
26,Niger,16666,12712,29378,12110,9350,21460
27,Ogun,21293,22558,43851,11826,13065,24891
28,Ondo,11734,12227,23961,9044,9763,18807
29,Osun,6097,6346,12443,2030,2440,4470
30,Oyo,27040,28017,55057,15102,16587,31689
31,Plateau,6441,5461,11902,5316,4568,9884
32,Rivers,25506,26502,52008,23265,24262,47527
33,Sokoto,1536,618,2154,1206,592,1798
34,Taraba,5823,4414,10237,4996,3884,8880
35,Yobe,10193,3972,14165,5507,2743,8250
36,Zamfara,14249,7610,21859,1616,1371,2987
37,Total,434896,403590,838486,326681,320447,647128

## PUBLICMATHS

In [49]:
pub_maths_21 = raw_21.iloc[:, 42:49].copy()

In [50]:
pub_maths_21.columns = [
  "state",
  "pub_cands_male",
  "pub_cands_female",
  "pub_cands_total",
  "pub_creds_5_maths_male",
  "pub_creds_5_maths_female",
  "pub_creds_5_maths_total"
]

In [51]:
pub_maths_21 = clean_states(pub_maths_21)

In [52]:
pub_maths_21 = clean_numeric(
    pub_maths_21, [
      "pub_cands_male",
      "pub_cands_female",
      "pub_cands_total",
      "pub_creds_5_maths_male",
      "pub_creds_5_maths_female",
      "pub_creds_5_maths_total"
    ]
)

In [53]:
pub_maths_21

,state,pub_cands_male,pub_cands_female,pub_cands_total,pub_creds_5_maths_male,pub_creds_5_maths_female,pub_creds_5_maths_total
0,Abia,4293,5078,9371,3797,4595,8392
1,Adamawa,24677,17967,42644,17830,13454,31284
2,Akwa Ibom,17101,18721,35822,14866,16552,31418
3,Anambra,8160,10809,18969,7750,10098,17848
4,Bauchi,7420,4848,12268,5379,3887,9266
5,Bayelsa,6462,6667,13129,5987,6201,12188
6,Benue,6020,4841,10861,5741,4503,10244
7,Borno,13282,10185,23467,9577,8261,17838
8,Cross River,8160,7970,16130,7528,7496,15024
9,Delta,16226,18564,34790,15044,17213,32257
10,Ebonyi,7111,7769,14880,6627,7440,14067
11,Edo,12049,13645,25694,11750,13372,25122
12,Ekiti,7221,7149,14370,5366,5569,10935
13,Enugu,9818,12241,22059,9296,11717,21013
14,FCT,6862,8731,15593,5607,6884,12491
15,Gombe,6531,5437,11968,4741,4503,9244
16,Imo,13458,14146,27604,11876,12486,24362
17,Jigawa,3720,1815,5535,3276,1702,4978
18,Kaduna,18699,15558,34257,15937,13222,29159
19,Kano,6089,6014,12103,5328,5585,10913
20,Katsina,8136,5838,13974,4668,3863,8531
21,Kebbi,18557,10667,29224,15229,9701,24930
22,Kogi,10574,9121,19695,9455,8275,17730
23,Kwara,8241,8129,16370,5114,5225,10339
24,Lagos,25856,29939,55795,20179,24366,44545
25,Nassarawa,13595,11304,24899,12356,10534,22890
26,Niger,16666,12712,29378,13198,9995,23193
27,Ogun,21293,22558,43851,13044,14215,27259
28,Ondo,11734,12227,23961,9729,10327,20056
29,Osun,6097,6346,12443,2331,2773,5104
30,Oyo,27040,28017,55057,16603,18199,34802
31,Plateau,6441,5461,11902,5522,4782,10304
32,Rivers,25506,26502,52008,23475,24522,47997
33,Sokoto,1536,618,2154,1087,592,1679
34,State,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
35,Taraba,5823,4414,10237,5282,4023,9305
36,Yobe,10193,3972,14165,6942,3167,10109
37,Zamfara,14249,7610,21859,2676,1534,4210
38,Total,434896,403590,838486,340193,330833,671026

In [54]:
pub_maths_21 = pub_maths_21.dropna(axis=0, how="any").reset_index(drop=True)

In [55]:
pub_maths_21

,state,pub_cands_male,pub_cands_female,pub_cands_total,pub_creds_5_maths_male,pub_creds_5_maths_female,pub_creds_5_maths_total
0,Abia,4293,5078,9371,3797,4595,8392
1,Adamawa,24677,17967,42644,17830,13454,31284
2,Akwa Ibom,17101,18721,35822,14866,16552,31418
3,Anambra,8160,10809,18969,7750,10098,17848
4,Bauchi,7420,4848,12268,5379,3887,9266
5,Bayelsa,6462,6667,13129,5987,6201,12188
6,Benue,6020,4841,10861,5741,4503,10244
7,Borno,13282,10185,23467,9577,8261,17838
8,Cross River,8160,7970,16130,7528,7496,15024
9,Delta,16226,18564,34790,15044,17213,32257
10,Ebonyi,7111,7769,14880,6627,7440,14067
11,Edo,12049,13645,25694,11750,13372,25122
12,Ekiti,7221,7149,14370,5366,5569,10935
13,Enugu,9818,12241,22059,9296,11717,21013
14,FCT,6862,8731,15593,5607,6884,12491
15,Gombe,6531,5437,11968,4741,4503,9244
16,Imo,13458,14146,27604,11876,12486,24362
17,Jigawa,3720,1815,5535,3276,1702,4978
18,Kaduna,18699,15558,34257,15937,13222,29159
19,Kano,6089,6014,12103,5328,5585,10913
20,Katsina,8136,5838,13974,4668,3863,8531
21,Kebbi,18557,10667,29224,15229,9701,24930
22,Kogi,10574,9121,19695,9455,8275,17730
23,Kwara,8241,8129,16370,5114,5225,10339
24,Lagos,25856,29939,55795,20179,24366,44545
25,Nassarawa,13595,11304,24899,12356,10534,22890
26,Niger,16666,12712,29378,13198,9995,23193
27,Ogun,21293,22558,43851,13044,14215,27259
28,Ondo,11734,12227,23961,9729,10327,20056
29,Osun,6097,6346,12443,2331,2773,5104
30,Oyo,27040,28017,55057,16603,18199,34802
31,Plateau,6441,5461,11902,5522,4782,10304
32,Rivers,25506,26502,52008,23475,24522,47997
33,Sokoto,1536,618,2154,1087,592,1679
34,Taraba,5823,4414,10237,5282,4023,9305
35,Yobe,10193,3972,14165,6942,3167,10109
36,Zamfara,14249,7610,21859,2676,1534,4210
37,Total,434896,403590,838486,340193,330833,671026

## PUBLIC ENGLISH AND MATHEMATICS

In [56]:
pub_eng_maths_21 = raw_21.iloc[:, 52:60].copy()

In [57]:
pub_eng_maths_21.columns = [
    "state",
    "pub_cand_male",
    "pub_cand_female",
    "pub_cand_total",
    "pub_cred_5_eng_maths_male",
    "pub_cred_5_eng_maths_female",
    "pub_cred_5_eng_maths_total",
    "pub_cred_5_eng_maths_pct"
]

In [58]:
pub_eng_maths_21 = clean_states(pub_eng_maths_21)

In [59]:
pub_eng_maths_21 = clean_numeric(
    pub_eng_maths_21,
    [
      "pub_cand_male",
      "pub_cand_female",
      "pub_cand_total",
      "pub_cred_5_eng_maths_male",
      "pub_cred_5_eng_maths_female",
      "pub_cred_5_eng_maths_total",
      "pub_cred_5_eng_maths_pct"
    ]
)

In [60]:
pub_eng_maths_21

,state,pub_cand_male,pub_cand_female,pub_cand_total,pub_cred_5_eng_maths_male,pub_cred_5_eng_maths_female,pub_cred_5_eng_maths_total,pub_cred_5_eng_maths_pct
0,Abia,4293,5078,9371,3647,4420,8067,86.08
1,Adamawa,24677,17967,42644,16490,12326,28816,67.57
2,Akwa Ibom,17101,18721,35822,14234,15891,30125,84.09
3,Anambra,8160,10809,18969,7573,9734,17307,91.23
4,Bauchi,7420,4848,12268,4808,3504,8312,67.75
5,Bayelsa,6462,6667,13129,5600,5741,11341,86.38
6,Benue,6020,4841,10861,5578,4386,9964,91.74
7,Borno,13282,10185,23467,8453,7336,15789,67.28
8,Cross River,8160,7970,16130,7300,7314,14614,90.6
9,Delta,16226,18564,34790,14199,16297,30496,87.65
10,Ebonyi,7111,7769,14880,6413,7179,13592,91.34
11,Edo,12049,13645,25694,11180,12838,24018,93.47
12,Ekiti,7221,7149,14370,5089,5351,10440,72.65
13,Enugu,9818,12241,22059,9179,11535,20714,93.9
14,FCT,6862,8731,15593,5438,6679,12117,77.7
15,Gombe,6531,5437,11968,4537,4210,8747,73.08
16,Imo,13458,14146,27604,11553,12156,23709,85.88
17,Jigawa,3720,1815,5535,2689,1274,3963,71.59
18,Kaduna,18699,15558,34257,14432,12027,26459,77.23
19,Kano,6089,6014,12103,4935,4821,9756,80.6
20,Katsina,8136,5838,13974,3818,3053,6871,49.16
21,Kebbi,18557,10667,29224,13887,8649,22536,77.11
22,Kogi,10574,9121,19695,8614,7610,16224,82.37
23,Kwara,8241,8129,16370,4352,4456,8808,53.8
24,Lagos,25856,29939,55795,19157,23154,42311,75.83
25,Nassarawa,13595,11304,24899,11506,9774,21280,85.46
26,Niger,16666,12712,29378,11571,9019,20590,70.08
27,Ogun,21293,22558,43851,11531,12672,24203,55.19
28,Ondo,11734,12227,23961,8785,9284,18069,75.41
29,Osun,6097,6346,12443,1834,2217,4051,32.55
30,Oyo,27040,28017,55057,14381,15774,30155,54.77
31,Plateau,6441,5461,11902,5076,4392,9468,79.54
32,Rivers,25506,26502,52008,22442,23381,45823,88.1
33,Sokoto,1536,618,2154,1057,590,1647,76.46
34,State,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
35,Taraba,5823,4414,10237,4837,3765,8602,84.02
36,Yobe,10193,3972,14165,5373,2499,7872,55.57
37,Zamfara,14249,7610,21859,1153,849,2002,9.15
38,Total,434896,403590,838486,312701,306157,618858,73.81

In [61]:
pub_eng_maths_21 = pub_eng_maths_21.dropna(axis=0, how="any").reset_index(drop=True)

In [62]:
pub_eng_maths_21.tail()

,state,pub_cand_male,pub_cand_female,pub_cand_total,pub_cred_5_eng_maths_male,pub_cred_5_eng_maths_female,pub_cred_5_eng_maths_total,pub_cred_5_eng_maths_pct
33,Sokoto,1536,618,2154,1057,590,1647,76.46
34,Taraba,5823,4414,10237,4837,3765,8602,84.02
35,Yobe,10193,3972,14165,5373,2499,7872,55.57
36,Zamfara,14249,7610,21859,1153,849,2002,9.15
37,Total,434896,403590,838486,312701,306157,618858,73.81

## COMGINING THE PRIVATE DATAFRAMES

In [63]:
priv_waec_21 = (
    priv_stud_21
    .merge(
        priv_eng_21[
            [
                "state",
                "priv_cred_5_eng_male",
                "priv_cred_5_eng_female",
                "priv_cred_5_eng_total"
            ]
        ],
        on="state",
        how="outer"
    )
    .merge(
        priv_maths_21[
            [
                "state",
                "priv_cred_5_maths_male",
                "priv_cred_5_maths_female",
                "priv_cred_5_maths_total"
            ]
        ],
        on="state",
        how="outer"
    )
    .merge(
        priv_eng_maths_21[
            [
                "state",
                "priv_cred_5_eng_maths_male",
                "priv_cred_5_eng_maths_female",
                "priv_cred_5_eng_maths_total",
                "priv_cred_5_eng_maths_pct"
            ]
        ],
        on="state",
        how="outer"
    )
)

In [65]:
priv_waec_21

,state,private_cand_male,private_cand_female,private_cand_total,priv_cred_5_eng_male,priv_cred_5_eng_female,priv_cred_5_eng_total,priv_cred_5_maths_male,priv_cred_5_maths_female,priv_cred_5_maths_total,priv_cred_5_eng_maths_male,priv_cred_5_eng_maths_female,priv_cred_5_eng_maths_total,priv_cred_5_eng_maths_pct
0,Abia,16589,18260,34849,15909,17517,33426,13580,14931,28511,13230,14486,27716,79.53
1,Adamawa,2822,2537,5359,2565,2361,4926,2599,2322,4921,2504,2254,4758,88.78
2,Akwa Ibom,7814,8124,15938,7295,7666,14961,7440,7756,15196,7176,7520,14696,92.2
3,Anambra,12157,14782,26939,11475,13957,25432,11572,14091,25663,11287,13724,25011,92.84
4,Bauchi,3994,3181,7175,3172,2662,5834,3295,2740,6035,3036,2560,5596,77.99
5,Bayelsa,1365,1561,2926,1165,1360,2525,1155,1317,2472,1118,1272,2390,81.68
6,Benue,15909,13521,29430,14746,12650,27396,15036,12850,27886,14480,12413,26893,91.37
7,Borno,5413,4658,10071,4249,3878,8127,4612,4123,8735,4091,3715,7806,77.5
8,Cross River,8555,9037,17592,7783,8441,16224,7952,8574,16526,7575,8242,15817,89.91
9,Delta,11396,12955,24351,10474,12151,22625,11031,12575,23606,10417,12047,22464,92.25
10,Ebonyi,4149,4551,8700,3957,4323,8280,3774,4166,7940,3699,4060,7759,89.18
11,Edo,16155,18578,34733,15028,17377,32405,15544,17958,33502,14848,17183,32031,92.22
12,Ekiti,3936,4206,8142,3774,4034,7808,2820,3028,5848,2759,2984,5743,70.53
13,Enugu,8313,9562,17875,7927,9148,17075,7721,8785,16506,7610,8692,16302,91.2
14,FCT,6187,6841,13028,5622,6250,11872,5358,5866,11224,5225,5726,10951,84.05
15,Gombe,1666,1440,3106,1533,1285,2818,1575,1344,2919,1505,1259,2764,88.98
16,Imo,8801,9953,18754,8297,9452,17749,7392,8300,15692,7212,8111,15323,81.7
17,Jigawa,462,380,842,389,329,718,407,337,744,361,308,669,79.45
18,Kaduna,17519,16837,34356,15879,15536,31415,15924,15377,31301,15100,14636,29736,86.55
19,Kano,6912,6871,13783,6321,6466,12787,6606,6673,13279,6251,6402,12653,91.8
20,Katsina,2305,2042,4347,1717,1647,3364,1697,1618,3315,1575,1522,3097,71.24
21,Kebbi,974,779,1753,937,762,1699,965,773,1738,935,761,1696,96.74
22,Kogi,4601,4487,9088,4131,4099,8230,4322,4229,8551,4070,4021,8091,89.02
23,Kwara,6623,6549,13172,5506,5550,11056,5088,5120,10208,4698,4714,9412,71.45
24,Lagos,56207,63192,119399,51255,58480,109735,51129,57656,108785,49019,55633,104652,87.64
25,Nassarawa,9264,9983,19247,8543,9276,17819,8593,9307,17900,8228,8931,17159,89.15
26,Niger,6662,7197,13859,5887,6394,12281,5946,6404,12350,5690,6134,11824,85.31
27,Ogun,35511,39142,74653,33691,37411,71102,33961,37508,71469,32955,36516,69471,93.05
28,Ondo,9356,9424,18780,8464,8714,17178,8488,8592,17080,8070,8242,16312,86.85
29,Osun,9296,10193,19489,6433,7336,13769,7036,7816,14852,6081,6780,12861,65.99
30,Oyo,18503,20200,38703,15525,17102,32627,16087,17620,33707,14750,16187,30937,79.93
31,Plateau,9233,8973,18206,8074,7927,16001,8320,8032,16352,7775,7561,15336,84.23
32,Rivers,13610,15223,28833,12734,14395,27129,12871,14364,27235,12320,13843,26163,90.73
33,Sokoto,1284,1090,2374,1260,1072,2332,1259,1062,2321,1251,1057,2308,97.21
34,State,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
35,Taraba,2677,2151,4828,2374,1941,4315,2506,2030,4536,2360,1930,4290,88.85
36,Total,349745,371921,721666,316393,341522,657915,316088,337970,654058,301047,323565,624612,86.55
37,Yobe,1611,2007,3618,1237,1602,2839,1449,1856,3305,1165,1512,2677,73.99
38,Zamfara,1832,1364,3196,1010,898,1908,929,813,1742,580,573,1153,36.08

In [71]:
# Dropping the state with missing values
priv_waec_21 = priv_waec_21.dropna(axis=0, how="any")

In [67]:
# Sorting 'Total' to the bottom
# Separating out the "Total" row so it isn't sorted alphabetically
total_row = priv_waec_21[priv_waec_21["state"] == "Total"]
priv_waec_21 = priv_waec_21[priv_waec_21["state"] != "Total"]

# Sorting the remaining states alphabetically
priv_waec_21 = priv_waec_21.sort_values("state")

# Appending "Total" back as the last row
priv_waec_21 = pd.concat([priv_waec_21, total_row])

# Resetting the index
priv_waec_21 = priv_waec_21.reset_index(drop=True)

In [72]:
priv_waec_21

,state,private_cand_male,private_cand_female,private_cand_total,priv_cred_5_eng_male,priv_cred_5_eng_female,priv_cred_5_eng_total,priv_cred_5_maths_male,priv_cred_5_maths_female,priv_cred_5_maths_total,priv_cred_5_eng_maths_male,priv_cred_5_eng_maths_female,priv_cred_5_eng_maths_total,priv_cred_5_eng_maths_pct
0,Abia,16589,18260,34849,15909,17517,33426,13580,14931,28511,13230,14486,27716,79.53
1,Adamawa,2822,2537,5359,2565,2361,4926,2599,2322,4921,2504,2254,4758,88.78
2,Akwa Ibom,7814,8124,15938,7295,7666,14961,7440,7756,15196,7176,7520,14696,92.2
3,Anambra,12157,14782,26939,11475,13957,25432,11572,14091,25663,11287,13724,25011,92.84
4,Bauchi,3994,3181,7175,3172,2662,5834,3295,2740,6035,3036,2560,5596,77.99
5,Bayelsa,1365,1561,2926,1165,1360,2525,1155,1317,2472,1118,1272,2390,81.68
6,Benue,15909,13521,29430,14746,12650,27396,15036,12850,27886,14480,12413,26893,91.37
7,Borno,5413,4658,10071,4249,3878,8127,4612,4123,8735,4091,3715,7806,77.5
8,Cross River,8555,9037,17592,7783,8441,16224,7952,8574,16526,7575,8242,15817,89.91
9,Delta,11396,12955,24351,10474,12151,22625,11031,12575,23606,10417,12047,22464,92.25
10,Ebonyi,4149,4551,8700,3957,4323,8280,3774,4166,7940,3699,4060,7759,89.18
11,Edo,16155,18578,34733,15028,17377,32405,15544,17958,33502,14848,17183,32031,92.22
12,Ekiti,3936,4206,8142,3774,4034,7808,2820,3028,5848,2759,2984,5743,70.53
13,Enugu,8313,9562,17875,7927,9148,17075,7721,8785,16506,7610,8692,16302,91.2
14,FCT,6187,6841,13028,5622,6250,11872,5358,5866,11224,5225,5726,10951,84.05
15,Gombe,1666,1440,3106,1533,1285,2818,1575,1344,2919,1505,1259,2764,88.98
16,Imo,8801,9953,18754,8297,9452,17749,7392,8300,15692,7212,8111,15323,81.7
17,Jigawa,462,380,842,389,329,718,407,337,744,361,308,669,79.45
18,Kaduna,17519,16837,34356,15879,15536,31415,15924,15377,31301,15100,14636,29736,86.55
19,Kano,6912,6871,13783,6321,6466,12787,6606,6673,13279,6251,6402,12653,91.8
20,Katsina,2305,2042,4347,1717,1647,3364,1697,1618,3315,1575,1522,3097,71.24
21,Kebbi,974,779,1753,937,762,1699,965,773,1738,935,761,1696,96.74
22,Kogi,4601,4487,9088,4131,4099,8230,4322,4229,8551,4070,4021,8091,89.02
23,Kwara,6623,6549,13172,5506,5550,11056,5088,5120,10208,4698,4714,9412,71.45
24,Lagos,56207,63192,119399,51255,58480,109735,51129,57656,108785,49019,55633,104652,87.64
25,Nassarawa,9264,9983,19247,8543,9276,17819,8593,9307,17900,8228,8931,17159,89.15
26,Niger,6662,7197,13859,5887,6394,12281,5946,6404,12350,5690,6134,11824,85.31
27,Ogun,35511,39142,74653,33691,37411,71102,33961,37508,71469,32955,36516,69471,93.05
28,Ondo,9356,9424,18780,8464,8714,17178,8488,8592,17080,8070,8242,16312,86.85
29,Osun,9296,10193,19489,6433,7336,13769,7036,7816,14852,6081,6780,12861,65.99
30,Oyo,18503,20200,38703,15525,17102,32627,16087,17620,33707,14750,16187,30937,79.93
31,Plateau,9233,8973,18206,8074,7927,16001,8320,8032,16352,7775,7561,15336,84.23
32,Rivers,13610,15223,28833,12734,14395,27129,12871,14364,27235,12320,13843,26163,90.73
33,Sokoto,1284,1090,2374,1260,1072,2332,1259,1062,2321,1251,1057,2308,97.21
35,Taraba,2677,2151,4828,2374,1941,4315,2506,2030,4536,2360,1930,4290,88.85
36,Yobe,1611,2007,3618,1237,1602,2839,1449,1856,3305,1165,1512,2677,73.99
37,Zamfara,1832,1364,3196,1010,898,1908,929,813,1742,580,573,1153,36.08
38,Total,349745,371921,721666,316393,341522,657915,316088,337970,654058,301047,323565,624612,86.55

In [69]:
from google.colab import files

In [73]:
file_name = "Cleaned 2021 Private WAEC Data.csv"

priv_waec_21.to_csv(file_name, index=False)
files.download(file_name)

## COMBINING PUBLIC

In [74]:
pub_waec_21 = (
    pub_cands_21
    .merge(
        pub_eng_21[
            [
                "state",
                "pub_creds_5_eng_male",
                "pub_creds_5_eng_female",
                "pub_creds_5_eng_total"
            ]
        ],
        on="state",
        how="outer"
    )
    .merge(
        pub_maths_21[
            [
                "state",
                "pub_creds_5_maths_male",
                "pub_creds_5_maths_female",
                "pub_creds_5_maths_total"
            ]
        ],
        on="state",
        how="outer"
    )
    .merge(
        pub_eng_maths_21[
            [
                "state",
                "pub_cred_5_eng_maths_male",
                "pub_cred_5_eng_maths_female",
                "pub_cred_5_eng_maths_total",
                "pub_cred_5_eng_maths_pct"
            ]
        ],
        on="state",
        how="outer"
    )
)

In [75]:
pub_waec_21

,state,pub_cands_male,pub_cands_female,pub_cands_total,pub_creds_5_eng_male,pub_creds_5_eng_female,pub_creds_5_eng_total,pub_creds_5_maths_male,pub_creds_5_maths_female,pub_creds_5_maths_total,pub_cred_5_eng_maths_male,pub_cred_5_eng_maths_female,pub_cred_5_eng_maths_total,pub_cred_5_eng_maths_pct
0,Abia,4293,5078,9371,4026,4802,8828,3797,4595,8392,3647,4420,8067,86.08
1,Adamawa,24677,17967,42644,17133,12864,29997,17830,13454,31284,16490,12326,28816,67.57
2,Akwa Ibom,17101,18721,35822,14576,16394,30970,14866,16552,31418,14234,15891,30125,84.09
3,Anambra,8160,10809,18969,7649,9971,17620,7750,10098,17848,7573,9734,17307,91.23
4,Bauchi,7420,4848,12268,5047,3668,8715,5379,3887,9266,4808,3504,8312,67.75
5,Bayelsa,6462,6667,13129,5657,5799,11456,5987,6201,12188,5600,5741,11341,86.38
6,Benue,6020,4841,10861,5664,4582,10246,5741,4503,10244,5578,4386,9964,91.74
7,Borno,13282,10185,23467,8708,7574,16282,9577,8261,17838,8453,7336,15789,67.28
8,Cross River,8160,7970,16130,7457,7477,14934,7528,7496,15024,7300,7314,14614,90.6
9,Delta,16226,18564,34790,14417,16694,31111,15044,17213,32257,14199,16297,30496,87.65
10,Ebonyi,7111,7769,14880,6513,7275,13788,6627,7440,14067,6413,7179,13592,91.34
11,Edo,12049,13645,25694,11215,12933,24148,11750,13372,25122,11180,12838,24018,93.47
12,Ekiti,7221,7149,14370,6405,6613,13018,5366,5569,10935,5089,5351,10440,72.65
13,Enugu,9818,12241,22059,9404,11804,21208,9296,11717,21013,9179,11535,20714,93.9
14,FCT,6862,8731,15593,5893,7386,13279,5607,6884,12491,5438,6679,12117,77.7
15,Gombe,6531,5437,11968,4839,4394,9233,4741,4503,9244,4537,4210,8747,73.08
16,Imo,13458,14146,27604,12723,13523,26246,11876,12486,24362,11553,12156,23709,85.88
17,Jigawa,3720,1815,5535,2834,1278,4112,3276,1702,4978,2689,1274,3963,71.59
18,Kaduna,18699,15558,34257,15297,13005,28302,15937,13222,29159,14432,12027,26459,77.23
19,Kano,6089,6014,12103,5041,4922,9963,5328,5585,10913,4935,4821,9756,80.6
20,Katsina,8136,5838,13974,4412,3320,7732,4668,3863,8531,3818,3053,6871,49.16
21,Kebbi,18557,10667,29224,14267,8707,22974,15229,9701,24930,13887,8649,22536,77.11
22,Kogi,10574,9121,19695,8742,7765,16507,9455,8275,17730,8614,7610,16224,82.37
23,Kwara,8241,8129,16370,4827,4962,9789,5114,5225,10339,4352,4456,8808,53.8
24,Lagos,25856,29939,55795,20137,24120,44257,20179,24366,44545,19157,23154,42311,75.83
25,Nassarawa,13595,11304,24899,11780,9990,21770,12356,10534,22890,11506,9774,21280,85.46
26,Niger,16666,12712,29378,12110,9350,21460,13198,9995,23193,11571,9019,20590,70.08
27,Ogun,21293,22558,43851,11826,13065,24891,13044,14215,27259,11531,12672,24203,55.19
28,Ondo,11734,12227,23961,9044,9763,18807,9729,10327,20056,8785,9284,18069,75.41
29,Osun,6097,6346,12443,2030,2440,4470,2331,2773,5104,1834,2217,4051,32.55
30,Oyo,27040,28017,55057,15102,16587,31689,16603,18199,34802,14381,15774,30155,54.77
31,Plateau,6441,5461,11902,5316,4568,9884,5522,4782,10304,5076,4392,9468,79.54
32,Rivers,25506,26502,52008,23265,24262,47527,23475,24522,47997,22442,23381,45823,88.1
33,Sokoto,1536,618,2154,1206,592,1798,1087,592,1679,1057,590,1647,76.46
34,State,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
35,Taraba,5823,4414,10237,4996,3884,8880,5282,4023,9305,4837,3765,8602,84.02
36,Total,434896,403590,838486,326681,320447,647128,340193,330833,671026,312701,306157,618858,73.81
37,Yobe,10193,3972,14165,5507,2743,8250,6942,3167,10109,5373,2499,7872,55.57
38,Zamfara,14249,7610,21859,1616,1371,2987,2676,1534,4210,1153,849,2002,9.15

In [76]:
pub_waec_21 = pub_waec_21.dropna(axis=0, how="any")

In [77]:
pub_waec_21

,state,pub_cands_male,pub_cands_female,pub_cands_total,pub_creds_5_eng_male,pub_creds_5_eng_female,pub_creds_5_eng_total,pub_creds_5_maths_male,pub_creds_5_maths_female,pub_creds_5_maths_total,pub_cred_5_eng_maths_male,pub_cred_5_eng_maths_female,pub_cred_5_eng_maths_total,pub_cred_5_eng_maths_pct
0,Abia,4293,5078,9371,4026,4802,8828,3797,4595,8392,3647,4420,8067,86.08
1,Adamawa,24677,17967,42644,17133,12864,29997,17830,13454,31284,16490,12326,28816,67.57
2,Akwa Ibom,17101,18721,35822,14576,16394,30970,14866,16552,31418,14234,15891,30125,84.09
3,Anambra,8160,10809,18969,7649,9971,17620,7750,10098,17848,7573,9734,17307,91.23
4,Bauchi,7420,4848,12268,5047,3668,8715,5379,3887,9266,4808,3504,8312,67.75
5,Bayelsa,6462,6667,13129,5657,5799,11456,5987,6201,12188,5600,5741,11341,86.38
6,Benue,6020,4841,10861,5664,4582,10246,5741,4503,10244,5578,4386,9964,91.74
7,Borno,13282,10185,23467,8708,7574,16282,9577,8261,17838,8453,7336,15789,67.28
8,Cross River,8160,7970,16130,7457,7477,14934,7528,7496,15024,7300,7314,14614,90.6
9,Delta,16226,18564,34790,14417,16694,31111,15044,17213,32257,14199,16297,30496,87.65
10,Ebonyi,7111,7769,14880,6513,7275,13788,6627,7440,14067,6413,7179,13592,91.34
11,Edo,12049,13645,25694,11215,12933,24148,11750,13372,25122,11180,12838,24018,93.47
12,Ekiti,7221,7149,14370,6405,6613,13018,5366,5569,10935,5089,5351,10440,72.65
13,Enugu,9818,12241,22059,9404,11804,21208,9296,11717,21013,9179,11535,20714,93.9
14,FCT,6862,8731,15593,5893,7386,13279,5607,6884,12491,5438,6679,12117,77.7
15,Gombe,6531,5437,11968,4839,4394,9233,4741,4503,9244,4537,4210,8747,73.08
16,Imo,13458,14146,27604,12723,13523,26246,11876,12486,24362,11553,12156,23709,85.88
17,Jigawa,3720,1815,5535,2834,1278,4112,3276,1702,4978,2689,1274,3963,71.59
18,Kaduna,18699,15558,34257,15297,13005,28302,15937,13222,29159,14432,12027,26459,77.23
19,Kano,6089,6014,12103,5041,4922,9963,5328,5585,10913,4935,4821,9756,80.6
20,Katsina,8136,5838,13974,4412,3320,7732,4668,3863,8531,3818,3053,6871,49.16
21,Kebbi,18557,10667,29224,14267,8707,22974,15229,9701,24930,13887,8649,22536,77.11
22,Kogi,10574,9121,19695,8742,7765,16507,9455,8275,17730,8614,7610,16224,82.37
23,Kwara,8241,8129,16370,4827,4962,9789,5114,5225,10339,4352,4456,8808,53.8
24,Lagos,25856,29939,55795,20137,24120,44257,20179,24366,44545,19157,23154,42311,75.83
25,Nassarawa,13595,11304,24899,11780,9990,21770,12356,10534,22890,11506,9774,21280,85.46
26,Niger,16666,12712,29378,12110,9350,21460,13198,9995,23193,11571,9019,20590,70.08
27,Ogun,21293,22558,43851,11826,13065,24891,13044,14215,27259,11531,12672,24203,55.19
28,Ondo,11734,12227,23961,9044,9763,18807,9729,10327,20056,8785,9284,18069,75.41
29,Osun,6097,6346,12443,2030,2440,4470,2331,2773,5104,1834,2217,4051,32.55
30,Oyo,27040,28017,55057,15102,16587,31689,16603,18199,34802,14381,15774,30155,54.77
31,Plateau,6441,5461,11902,5316,4568,9884,5522,4782,10304,5076,4392,9468,79.54
32,Rivers,25506,26502,52008,23265,24262,47527,23475,24522,47997,22442,23381,45823,88.1
33,Sokoto,1536,618,2154,1206,592,1798,1087,592,1679,1057,590,1647,76.46
35,Taraba,5823,4414,10237,4996,3884,8880,5282,4023,9305,4837,3765,8602,84.02
36,Total,434896,403590,838486,326681,320447,647128,340193,330833,671026,312701,306157,618858,73.81
37,Yobe,10193,3972,14165,5507,2743,8250,6942,3167,10109,5373,2499,7872,55.57
38,Zamfara,14249,7610,21859,1616,1371,2987,2676,1534,4210,1153,849,2002,9.15

In [78]:
total_row = pub_waec_21[pub_waec_21["state"] == "Total"]
pub_waec_21 = pub_waec_21[pub_waec_21["state"] != "Total"]

pub_waec_21 = pd.concat([pub_waec_21, total_row]).reset_index(drop=True)

In [79]:
pub_waec_21

,state,pub_cands_male,pub_cands_female,pub_cands_total,pub_creds_5_eng_male,pub_creds_5_eng_female,pub_creds_5_eng_total,pub_creds_5_maths_male,pub_creds_5_maths_female,pub_creds_5_maths_total,pub_cred_5_eng_maths_male,pub_cred_5_eng_maths_female,pub_cred_5_eng_maths_total,pub_cred_5_eng_maths_pct
0,Abia,4293,5078,9371,4026,4802,8828,3797,4595,8392,3647,4420,8067,86.08
1,Adamawa,24677,17967,42644,17133,12864,29997,17830,13454,31284,16490,12326,28816,67.57
2,Akwa Ibom,17101,18721,35822,14576,16394,30970,14866,16552,31418,14234,15891,30125,84.09
3,Anambra,8160,10809,18969,7649,9971,17620,7750,10098,17848,7573,9734,17307,91.23
4,Bauchi,7420,4848,12268,5047,3668,8715,5379,3887,9266,4808,3504,8312,67.75
5,Bayelsa,6462,6667,13129,5657,5799,11456,5987,6201,12188,5600,5741,11341,86.38
6,Benue,6020,4841,10861,5664,4582,10246,5741,4503,10244,5578,4386,9964,91.74
7,Borno,13282,10185,23467,8708,7574,16282,9577,8261,17838,8453,7336,15789,67.28
8,Cross River,8160,7970,16130,7457,7477,14934,7528,7496,15024,7300,7314,14614,90.6
9,Delta,16226,18564,34790,14417,16694,31111,15044,17213,32257,14199,16297,30496,87.65
10,Ebonyi,7111,7769,14880,6513,7275,13788,6627,7440,14067,6413,7179,13592,91.34
11,Edo,12049,13645,25694,11215,12933,24148,11750,13372,25122,11180,12838,24018,93.47
12,Ekiti,7221,7149,14370,6405,6613,13018,5366,5569,10935,5089,5351,10440,72.65
13,Enugu,9818,12241,22059,9404,11804,21208,9296,11717,21013,9179,11535,20714,93.9
14,FCT,6862,8731,15593,5893,7386,13279,5607,6884,12491,5438,6679,12117,77.7
15,Gombe,6531,5437,11968,4839,4394,9233,4741,4503,9244,4537,4210,8747,73.08
16,Imo,13458,14146,27604,12723,13523,26246,11876,12486,24362,11553,12156,23709,85.88
17,Jigawa,3720,1815,5535,2834,1278,4112,3276,1702,4978,2689,1274,3963,71.59
18,Kaduna,18699,15558,34257,15297,13005,28302,15937,13222,29159,14432,12027,26459,77.23
19,Kano,6089,6014,12103,5041,4922,9963,5328,5585,10913,4935,4821,9756,80.6
20,Katsina,8136,5838,13974,4412,3320,7732,4668,3863,8531,3818,3053,6871,49.16
21,Kebbi,18557,10667,29224,14267,8707,22974,15229,9701,24930,13887,8649,22536,77.11
22,Kogi,10574,9121,19695,8742,7765,16507,9455,8275,17730,8614,7610,16224,82.37
23,Kwara,8241,8129,16370,4827,4962,9789,5114,5225,10339,4352,4456,8808,53.8
24,Lagos,25856,29939,55795,20137,24120,44257,20179,24366,44545,19157,23154,42311,75.83
25,Nassarawa,13595,11304,24899,11780,9990,21770,12356,10534,22890,11506,9774,21280,85.46
26,Niger,16666,12712,29378,12110,9350,21460,13198,9995,23193,11571,9019,20590,70.08
27,Ogun,21293,22558,43851,11826,13065,24891,13044,14215,27259,11531,12672,24203,55.19
28,Ondo,11734,12227,23961,9044,9763,18807,9729,10327,20056,8785,9284,18069,75.41
29,Osun,6097,6346,12443,2030,2440,4470,2331,2773,5104,1834,2217,4051,32.55
30,Oyo,27040,28017,55057,15102,16587,31689,16603,18199,34802,14381,15774,30155,54.77
31,Plateau,6441,5461,11902,5316,4568,9884,5522,4782,10304,5076,4392,9468,79.54
32,Rivers,25506,26502,52008,23265,24262,47527,23475,24522,47997,22442,23381,45823,88.1
33,Sokoto,1536,618,2154,1206,592,1798,1087,592,1679,1057,590,1647,76.46
34,Taraba,5823,4414,10237,4996,3884,8880,5282,4023,9305,4837,3765,8602,84.02
35,Yobe,10193,3972,14165,5507,2743,8250,6942,3167,10109,5373,2499,7872,55.57
36,Zamfara,14249,7610,21859,1616,1371,2987,2676,1534,4210,1153,849,2002,9.15
37,Total,434896,403590,838486,326681,320447,647128,340193,330833,671026,312701,306157,618858,73.81

In [80]:
file_name = "Cleaned 2021 Public WAEC Data.csv"

pub_waec_21.to_csv(file_name, index=False)
files.download(file_name)