# IMPORTING THE REQUIRED LIBRARIES

In [ ]:
import pandas as pd
import numpy as np
from google.colab import files

# 2016 PUBLIC SCHOOL STUDENTS

In [ ]:
# Loading the dataset
pub_students_16 = pd.read_csv("//content/2016 Public Student Data.csv")

In [ ]:
# Viewing the first ten rows
pub_students_16.head(10)

,Unnamed: 0,No. of,Unnamed: 2,SSSI,Unnamed: 4,Unnamed: 5,SSS2,Unnamed: 7,Unnamed: 8,SSS3,Unnamed: 10,Unnamed: 11,Total,Unnamed: 13
0,State,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,Schools,M,F,NaN,M,F,NaN,M,F,NaN,M,F,M+F
2,Abia,164,"2,124","3,148",NaN,"1,774","2,794",NaN,"1,614","2,245",NaN,"5,512","8,187","13,699"
3,Adamawa,273,"12,753","10,028",NaN,"17,246","12,291",NaN,"13,067","10,415",NaN,"43,066","32,734","75,800"
4,Akwa Ibom,241,"24,971","26,538",NaN,"76,065","24,588",NaN,"24,046","22,840",NaN,"125,082","73,966","199,048"
5,Anambra,257,"9,874","11,358",NaN,"8,362","10,078",NaN,"5,691","7,095",NaN,"23,927","28,531","52,458"
6,Bauchi,176,"21,590","12,724",NaN,"20,363","10,950",NaN,"19,873","9,537",NaN,"61,826","33,211","95,037"
7,Bayelsa,160,"5,072","4,649",NaN,"5,201","5,027",NaN,"5,858","4,902",NaN,"16,131","14,578","30,709"
8,Benue,311,"9,196","7,012",NaN,"8,557","6,643",NaN,"7,781","5,992",NaN,"25,534","19,647","45,181"
9,Borno,84,"13,582","10,446",NaN,"13,276","8,683",NaN,"10,144","7,177",NaN,"37,002","26,306","63,308"

In [ ]:
# Checking the number of rows and columns
pub_students_16.shape

(40, 14)

In [ ]:
# Dropping the rows filled with missing values
pub_students_16 = pub_students_16.dropna(axis=1, how="all")

In [ ]:
# Viewing the result
pub_students_16.head(10)

,Unnamed: 0,No. of,Unnamed: 2,SSSI,Unnamed: 5,SSS2,Unnamed: 8,SSS3,Unnamed: 11,Total,Unnamed: 13
0,State,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,Schools,M,F,M,F,M,F,M,F,M+F
2,Abia,164,"2,124","3,148","1,774","2,794","1,614","2,245","5,512","8,187","13,699"
3,Adamawa,273,"12,753","10,028","17,246","12,291","13,067","10,415","43,066","32,734","75,800"
4,Akwa Ibom,241,"24,971","26,538","76,065","24,588","24,046","22,840","125,082","73,966","199,048"
5,Anambra,257,"9,874","11,358","8,362","10,078","5,691","7,095","23,927","28,531","52,458"
6,Bauchi,176,"21,590","12,724","20,363","10,950","19,873","9,537","61,826","33,211","95,037"
7,Bayelsa,160,"5,072","4,649","5,201","5,027","5,858","4,902","16,131","14,578","30,709"
8,Benue,311,"9,196","7,012","8,557","6,643","7,781","5,992","25,534","19,647","45,181"
9,Borno,84,"13,582","10,446","13,276","8,683","10,144","7,177","37,002","26,306","63,308"

In [ ]:
pub_students_16.columns = [
    "state",
    "num_schools",
    "ss1_male",
    "ss1_female",
    "ss2_male",
    "ss2_female",
    "ss3_male",
    "ss3_female",
    "total_male",
    "total_female",
    "total_students"
]

In [ ]:
# Viewing the result
pub_students_16.head(10)

,state,num_schools,ss1_male,ss1_female,ss2_male,ss2_female,ss3_male,ss3_female,total_male,total_female,total_students
0,State,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,Schools,M,F,M,F,M,F,M,F,M+F
2,Abia,164,"2,124","3,148","1,774","2,794","1,614","2,245","5,512","8,187","13,699"
3,Adamawa,273,"12,753","10,028","17,246","12,291","13,067","10,415","43,066","32,734","75,800"
4,Akwa Ibom,241,"24,971","26,538","76,065","24,588","24,046","22,840","125,082","73,966","199,048"
5,Anambra,257,"9,874","11,358","8,362","10,078","5,691","7,095","23,927","28,531","52,458"
6,Bauchi,176,"21,590","12,724","20,363","10,950","19,873","9,537","61,826","33,211","95,037"
7,Bayelsa,160,"5,072","4,649","5,201","5,027","5,858","4,902","16,131","14,578","30,709"
8,Benue,311,"9,196","7,012","8,557","6,643","7,781","5,992","25,534","19,647","45,181"
9,Borno,84,"13,582","10,446","13,276","8,683","10,144","7,177","37,002","26,306","63,308"

In [ ]:
# Dropping the first two rows
pub_students_16 = pub_students_16.iloc[2:].reset_index(drop=True)

In [ ]:
# Viewing the result
pub_students_16.head(10)

,state,num_schools,ss1_male,ss1_female,ss2_male,ss2_female,ss3_male,ss3_female,total_male,total_female,total_students
0,Abia,164,"2,124","3,148","1,774","2,794","1,614","2,245","5,512","8,187","13,699"
1,Adamawa,273,"12,753","10,028","17,246","12,291","13,067","10,415","43,066","32,734","75,800"
2,Akwa Ibom,241,"24,971","26,538","76,065","24,588","24,046","22,840","125,082","73,966","199,048"
3,Anambra,257,"9,874","11,358","8,362","10,078","5,691","7,095","23,927","28,531","52,458"
4,Bauchi,176,"21,590","12,724","20,363","10,950","19,873","9,537","61,826","33,211","95,037"
5,Bayelsa,160,"5,072","4,649","5,201","5,027","5,858","4,902","16,131","14,578","30,709"
6,Benue,311,"9,196","7,012","8,557","6,643","7,781","5,992","25,534","19,647","45,181"
7,Borno,84,"13,582","10,446","13,276","8,683","10,144","7,177","37,002","26,306","63,308"
8,Cross River,217,"7,909","7,218","6,352","6,192","4,278","4,146","18,539","17,556","36,095"
9,Delta,383,"18,112","17,082","17,408","18,100","13,171","12,243","48,691","47,425","96,116"

In [ ]:
pub_students_16.tail(10)

,state,num_schools,ss1_male,ss1_female,ss2_male,ss2_female,ss3_male,ss3_female,total_male,total_female,total_students
28,Ondo,308,"17,876","18,056","17,505","17,582","12,220","11,872","47,601","47,510","95,111"
29,Osun,231,"14,013","13,208","14,541","13,610","12,065","10,381","40,619","37,199","77,818"
30,Oyo,565,"34,862","35,011","31,280","31,890","26,372","27,795","92,514","94,696","187,210"
31,Plateau,305,"8,943","7,124","8,921","7,168","8,001","6,244","25,865","20,536","46,401"
32,Rivers,234,"11,230","13,243","13,863","22,172","13,759","14,743","38,852","50,158","89,010"
33,Sokoto,86,"16,352","9,017","15,179","8,254","16,078","7,795","47,609","25,066","72,675"
34,Taraba,185,"7,206","5,118","6,549","4,571","5,504","3,833","19,259","13,522","32,781"
35,Yobe,50,"10,139","5,035","8,791","3,805","7,205","3,015","26,135","11,855","37,990"
36,Zamfara,146,"17,820","7,335","17,269","7,326","18,073","7,674","53,162","22,335","75,497"
37,National,"8,930","688,763","597,800","697,791","560,559","563,539","455,296","1,950,093","1,613,655","3,563,748"

In [ ]:
# Viewing info about the dataset
pub_students_16.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 38 entries, 0 to 37
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   state           38 non-null     object
 1   num_schools     38 non-null     object
 2   ss1_male        38 non-null     object
 3   ss1_female      38 non-null     object
 4   ss2_male        38 non-null     object
 5   ss2_female      38 non-null     object
 6   ss3_male        38 non-null     object
 7   ss3_female      38 non-null     object
 8   total_male      38 non-null     object
 9   total_female    38 non-null     object
 10  total_students  38 non-null     object
dtypes: object(11)
memory usage: 3.4+ KB

In [ ]:
# Converting the numerical columns
num_cols = [
    "num_schools",
    "ss1_male",
    "ss1_female",
    "ss2_male",
    "ss2_female",
    "ss3_male",
    "ss3_female",
    "total_male",
    "total_female",
    "total_students"
]

for col in num_cols:
  pub_students_16[col] = pub_students_16[col].astype(str).str.replace(",", "", regex=False)
  pub_students_16[col] = pd.to_numeric(pub_students_16[col], errors="coerce")

In [ ]:
# Viewing the result
pub_students_16.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 38 entries, 0 to 37
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   state           38 non-null     object
 1   num_schools     38 non-null     int64
 2   ss1_male        38 non-null     int64
 3   ss1_female      38 non-null     int64
 4   ss2_male        38 non-null     int64
 5   ss2_female      38 non-null     int64
 6   ss3_male        38 non-null     int64
 7   ss3_female      38 non-null     int64
 8   total_male      38 non-null     int64
 9   total_female    38 non-null     int64
 10  total_students  38 non-null     int64
dtypes: int64(10), object(1)
memory usage: 3.4+ KB

In [ ]:
pub_students_16.head(10)

,state,num_schools,ss1_male,ss1_female,ss2_male,ss2_female,ss3_male,ss3_female,total_male,total_female,total_students
0,Abia,164,2124,3148,1774,2794,1614,2245,5512,8187,13699
1,Adamawa,273,12753,10028,17246,12291,13067,10415,43066,32734,75800
2,Akwa Ibom,241,24971,26538,76065,24588,24046,22840,125082,73966,199048
3,Anambra,257,9874,11358,8362,10078,5691,7095,23927,28531,52458
4,Bauchi,176,21590,12724,20363,10950,19873,9537,61826,33211,95037
5,Bayelsa,160,5072,4649,5201,5027,5858,4902,16131,14578,30709
6,Benue,311,9196,7012,8557,6643,7781,5992,25534,19647,45181
7,Borno,84,13582,10446,13276,8683,10144,7177,37002,26306,63308
8,Cross River,217,7909,7218,6352,6192,4278,4146,18539,17556,36095
9,Delta,383,18112,17082,17408,18100,13171,12243,48691,47425,96116

In [ ]:
pub_students_16.to_csv("Cleaned 2016 Public Student Data.csv", index=False)
files.download("Cleaned 2016 Public Student Data.csv")

# 2016 PRIVATE SCHOOL STUDENTS

In [ ]:
# Loading the dataset
priv_students_16 = pd.read_csv("/content/2016 Private Student Data.csv")

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
# Viewing the first ten rows of the dataset
priv_students_16.head(10)

,Unnamed: 0,No. of,Unnamed: 2,SSSI,Unnamed: 4,Unnamed: 5,SSS2,Unnamed: 7,Unnamed: 8,SSS3,Unnamed: 10,Unnamed: 11,Total,Unnamed: 13
0,State,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,Schools,M,F,NaN,M,F,NaN,M,F,NaN,M,F,M+F
2,Abia,194,"2,242","2,356",NaN,"2,215","2,566",NaN,"2,611","2,808",NaN,"7,068","7,730","14,798"
3,Adamawa,96,989,884,NaN,845,802,NaN,646,579,NaN,"2,480","2,265","4,745"
4,Akwa Ibom,87,"1,562","1,737",NaN,"1,673","1,823",NaN,"1,799","2,249",NaN,"5,034","5,809","10,843"
5,Anambra,541,"1,058",978,NaN,"1,104",977,NaN,"1,078","1,120",NaN,"3,240","3,075","6,315"
6,Bauchi,188,"4,882","5,240",NaN,"4,354","4,669",NaN,"4,068","4,296",NaN,"13,304","14,205","27,509"
7,Bayelsa,62,444,436,NaN,312,334,NaN,99,114,NaN,855,884,"1,739"
8,Benue,494,"10,290","9,095",NaN,"9,469","8,192",NaN,"8,495","7,487",NaN,"28,254","24,774","53,028"
9,Borno,26,915,909,NaN,"1,093",994,NaN,716,601,NaN,"2,724","2,504","5,228"

In [ ]:
# Dropping the rows filled with missing values
priv_students_16 = priv_students_16.dropna(axis=1, how="all")

In [ ]:
# Viewing the result
priv_students_16.head(10)

,Unnamed: 0,No. of,Unnamed: 2,SSSI,Unnamed: 5,SSS2,Unnamed: 8,SSS3,Unnamed: 11,Total,Unnamed: 13
0,State,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,Schools,M,F,M,F,M,F,M,F,M+F
2,Abia,194,"2,242","2,356","2,215","2,566","2,611","2,808","7,068","7,730","14,798"
3,Adamawa,96,989,884,845,802,646,579,"2,480","2,265","4,745"
4,Akwa Ibom,87,"1,562","1,737","1,673","1,823","1,799","2,249","5,034","5,809","10,843"
5,Anambra,541,"1,058",978,"1,104",977,"1,078","1,120","3,240","3,075","6,315"
6,Bauchi,188,"4,882","5,240","4,354","4,669","4,068","4,296","13,304","14,205","27,509"
7,Bayelsa,62,444,436,312,334,99,114,855,884,"1,739"
8,Benue,494,"10,290","9,095","9,469","8,192","8,495","7,487","28,254","24,774","53,028"
9,Borno,26,915,909,"1,093",994,716,601,"2,724","2,504","5,228"

In [ ]:
# Renaming the columns
priv_students_16.columns = [
    "state",
    "num_schools",
    "ss1_male",
    "ss1_female",
    "ss2_male",
    "ss2_female",
    "ss3_male",
    "ss3_female",
    "total_male",
    "total_female",
    "total_students"
]

In [ ]:
# Viewing the result
priv_students_16.head(10)

,state,num_schools,ss1_male,ss1_female,ss2_male,ss2_female,ss3_male,ss3_female,total_male,total_female,total_students
0,State,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,Schools,M,F,M,F,M,F,M,F,M+F
2,Abia,194,"2,242","2,356","2,215","2,566","2,611","2,808","7,068","7,730","14,798"
3,Adamawa,96,989,884,845,802,646,579,"2,480","2,265","4,745"
4,Akwa Ibom,87,"1,562","1,737","1,673","1,823","1,799","2,249","5,034","5,809","10,843"
5,Anambra,541,"1,058",978,"1,104",977,"1,078","1,120","3,240","3,075","6,315"
6,Bauchi,188,"4,882","5,240","4,354","4,669","4,068","4,296","13,304","14,205","27,509"
7,Bayelsa,62,444,436,312,334,99,114,855,884,"1,739"
8,Benue,494,"10,290","9,095","9,469","8,192","8,495","7,487","28,254","24,774","53,028"
9,Borno,26,915,909,"1,093",994,716,601,"2,724","2,504","5,228"

In [ ]:
# Dropping the first two rows
priv_students_16 = priv_students_16.iloc[2:].reset_index(drop=True)

In [ ]:
# Viewing the result
priv_students_16.head(10)

,state,num_schools,ss1_male,ss1_female,ss2_male,ss2_female,ss3_male,ss3_female,total_male,total_female,total_students
0,Abia,194,"2,242","2,356","2,215","2,566","2,611","2,808","7,068","7,730","14,798"
1,Adamawa,96,989,884,845,802,646,579,"2,480","2,265","4,745"
2,Akwa Ibom,87,"1,562","1,737","1,673","1,823","1,799","2,249","5,034","5,809","10,843"
3,Anambra,541,"1,058",978,"1,104",977,"1,078","1,120","3,240","3,075","6,315"
4,Bauchi,188,"4,882","5,240","4,354","4,669","4,068","4,296","13,304","14,205","27,509"
5,Bayelsa,62,444,436,312,334,99,114,855,884,"1,739"
6,Benue,494,"10,290","9,095","9,469","8,192","8,495","7,487","28,254","24,774","53,028"
7,Borno,26,915,909,"1,093",994,716,601,"2,724","2,504","5,228"
8,Cross River,164,"2,541","2,593","2,365","2,434","2,508","2,661","7,414","7,688","15,102"
9,Delta,403,"5,009","5,021","4,633","4,738","4,393","4,663","14,035","14,422","28,457"

In [ ]:
priv_students_16.tail(10)

,state,num_schools,ss1_male,ss1_female,ss2_male,ss2_female,ss3_male,ss3_female,total_male,total_female,total_students
28,Ondo,175,"2,057","2,052","2,141","2,243","2,055","2,036","6,253","6,331","12,584"
29,Osun,124,"1,210","1,226","1,293","1,353","1,068","1,196","3,571","3,775","7,346"
30,Oyo,"3,350","10,093","10,219","8,544","9,367","8,377","9,321","27,014","28,907","55,921"
31,Plateau,406,"6,717","6,844","6,656","6,365","5,344","5,185","18,717","18,394","37,111"
32,Rivers,438,"4,247","4,467","4,390","4,037","3,596","3,762","12,233","12,266","24,499"
33,Sokoto,43,993,"1,038",935,940,703,804,"2,631","2,782","5,413"
34,Taraba,195,"3,913","3,267","3,184","2,657","3,019","2,509","10,116","8,433","18,549"
35,Yobe,32,928,"1,144",722,"1,023",732,"1,041","2,382","3,208","5,590"
36,Zamfara,104,"17,820","7,335","17,269","7,326","18,073","7,674","53,162","22,335","75,497"
37,National,"12,758","164,672","156,319","155,494","148,735","146,933","139,408","467,099","444,462","911,561"

In [ ]:
# Viewing the data types of the dataframe
priv_students_16.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 38 entries, 0 to 37
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   state           38 non-null     object
 1   num_schools     38 non-null     object
 2   ss1_male        37 non-null     object
 3   ss1_female      38 non-null     object
 4   ss2_male        38 non-null     object
 5   ss2_female      38 non-null     object
 6   ss3_male        38 non-null     object
 7   ss3_female      38 non-null     object
 8   total_male      38 non-null     object
 9   total_female    38 non-null     object
 10  total_students  38 non-null     object
dtypes: object(11)
memory usage: 3.4+ KB

In [ ]:
# Converting the numeric columns into their appropriate data type
for col in num_cols:
  priv_students_16[col] = priv_students_16[col].astype(str).str.replace(",", "", regex=False) # Removing the commas
  priv_students_16[col] = pd.to_numeric(priv_students_16[col], errors="coerce") # Converting the data type

In [ ]:
# Viewing the result
priv_students_16.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 38 entries, 0 to 37
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   state           38 non-null     object
 1   num_schools     38 non-null     int64
 2   ss1_male        37 non-null     float64
 3   ss1_female      37 non-null     float64
 4   ss2_male        38 non-null     int64
 5   ss2_female      38 non-null     int64
 6   ss3_male        38 non-null     int64
 7   ss3_female      38 non-null     int64
 8   total_male      38 non-null     int64
 9   total_female    38 non-null     int64
 10  total_students  38 non-null     int64
dtypes: float64(2), int64(8), object(1)
memory usage: 3.4+ KB

In [ ]:
priv_students_16.head(10)

,state,num_schools,ss1_male,ss1_female,ss2_male,ss2_female,ss3_male,ss3_female,total_male,total_female,total_students
0,Abia,194,2242.0,2356.0,2215,2566,2611,2808,7068,7730,14798
1,Adamawa,96,989.0,884.0,845,802,646,579,2480,2265,4745
2,Akwa Ibom,87,1562.0,1737.0,1673,1823,1799,2249,5034,5809,10843
3,Anambra,541,1058.0,978.0,1104,977,1078,1120,3240,3075,6315
4,Bauchi,188,4882.0,5240.0,4354,4669,4068,4296,13304,14205,27509
5,Bayelsa,62,444.0,436.0,312,334,99,114,855,884,1739
6,Benue,494,10290.0,9095.0,9469,8192,8495,7487,28254,24774,53028
7,Borno,26,915.0,909.0,1093,994,716,601,2724,2504,5228
8,Cross River,164,2541.0,2593.0,2365,2434,2508,2661,7414,7688,15102
9,Delta,403,5009.0,5021.0,4633,4738,4393,4663,14035,14422,28457

In [ ]:
priv_students_16.isna().sum()

state             0
num_schools       0
ss1_male          1
ss1_female        1
ss2_male          0
ss2_female        0
ss3_male          0
ss3_female        0
total_male        0
total_female      0
total_students    0
dtype: int64

In [ ]:
priv_students_16

,state,num_schools,ss1_male,ss1_female,ss2_male,ss2_female,ss3_male,ss3_female,total_male,total_female,total_students
0,Abia,194,2242.0,2356.0,2215,2566,2611,2808,7068,7730,14798
1,Adamawa,96,989.0,884.0,845,802,646,579,2480,2265,4745
2,Akwa Ibom,87,1562.0,1737.0,1673,1823,1799,2249,5034,5809,10843
3,Anambra,541,1058.0,978.0,1104,977,1078,1120,3240,3075,6315
4,Bauchi,188,4882.0,5240.0,4354,4669,4068,4296,13304,14205,27509
5,Bayelsa,62,444.0,436.0,312,334,99,114,855,884,1739
6,Benue,494,10290.0,9095.0,9469,8192,8495,7487,28254,24774,53028
7,Borno,26,915.0,909.0,1093,994,716,601,2724,2504,5228
8,Cross River,164,2541.0,2593.0,2365,2434,2508,2661,7414,7688,15102
9,Delta,403,5009.0,5021.0,4633,4738,4393,4663,14035,14422,28457
10,Ebonyi,133,4168.0,4376.0,4178,4726,3887,3980,12233,13082,25315
11,Edo,456,7520.0,7191.0,7226,7226,8330,8000,23076,22417,45493
12,Ekiti,164,1107.0,1133.0,1292,1508,1273,1288,3672,3929,7601
13,Enugu,288,6158.0,7030.0,6307,7046,6364,7465,18829,21541,40370
14,FCT,43,282.0,289.0,298,265,179,179,759,733,1492
15,Gombe,112,2824.0,2790.0,2767,2559,2369,2238,7960,7587,15547
16,Imo,31,386.0,405.0,339,374,330,379,1055,1158,2213
17,Jigawa,3,NaN,NaN,60,35,69,44,209,144,353
18,Kaduna,386,7639.0,7053.0,6846,6459,5437,5317,19922,18829,38751
19,Kano,304,5896.0,7473.0,4835,5911,4518,5094,15249,18478,33727
20,Katsina,147,4048.0,3525.0,3547,2892,3593,2506,11188,8923,20111
21,Kebbi,27,602.0,421.0,436,376,263,323,1301,1120,2421
22,Kogi,209,2919.0,3118.0,2730,2906,2601,2555,8250,8579,16829
23,Kwara,186,2807.0,2673.0,2397,2271,2099,1960,7303,6904,14207
24,Lagos,1908,22483.0,24144.0,21319,22978,17240,18453,61042,65575,126617
25,Nasarawa,237,3026.0,2720.0,2530,2386,2162,2051,7718,7157,14875
26,Niger,198,2914.0,2968.0,2395,2386,2117,2213,7426,7567,14993
27,Ogun,804,11903.0,12104.0,12795,13591,14722,15257,39420,40952,80372
28,Ondo,175,2057.0,2052.0,2141,2243,2055,2036,6253,6331,12584
29,Osun,124,1210.0,1226.0,1293,1353,1068,1196,3571,3775,7346
30,Oyo,3350,10093.0,10219.0,8544,9367,8377,9321,27014,28907,55921
31,Plateau,406,6717.0,6844.0,6656,6365,5344,5185,18717,18394,37111
32,Rivers,438,4247.0,4467.0,4390,4037,3596,3762,12233,12266,24499
33,Sokoto,43,993.0,1038.0,935,940,703,804,2631,2782,5413
34,Taraba,195,3913.0,3267.0,3184,2657,3019,2509,10116,8433,18549
35,Yobe,32,928.0,1144.0,722,1023,732,1041,2382,3208,5590
36,Zamfara,104,17820.0,7335.0,17269,7326,18073,7674,53162,22335,75497
37,National,12758,164672.0,156319.0,155494,148735,146933,139408,467099,444462,911561

# 2016 TEACHER DATA

In [ ]:
# Loading the dataset
teachers_16 = pd.read_csv("/content/2016 Teacher Data.csv")

In [ ]:
# Viewing the first five rows
teachers_16.head(5)

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Public,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Private,Unnamed: 10
0,State,NaN,All Teachers,NaN,NaN,Qualified Teachers,NaN,NaN,All Teachers,Qualified Teachers,NaN
1,NaN,M,F,M+F,M,NaN,F M+F,M,F,M+F M,F M+F
2,Abia,444,"1,209","1,653",380,NaN,"1,003 1,383","1,481","1,953","3,434 377","638 1,015"
3,Adamawa,"2,260",905,"3,165","2,048",NaN,"789 2,837",780,571,"1,351 234",133 367
4,Akwa Ibom,"1,960","1,477","3,437","1,442",NaN,"1,105 2,547","1,168",786,"1,954 273",227 500

In [ ]:
# Dropping the column with missing values
teachers_16 = teachers_16.dropna(axis=1, how="all")

In [ ]:
# Viewing the result
teachers_16.head()

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Public,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Private,Unnamed: 10
0,State,NaN,All Teachers,NaN,NaN,Qualified Teachers,NaN,NaN,All Teachers,Qualified Teachers,NaN
1,NaN,M,F,M+F,M,NaN,F M+F,M,F,M+F M,F M+F
2,Abia,444,"1,209","1,653",380,NaN,"1,003 1,383","1,481","1,953","3,434 377","638 1,015"
3,Adamawa,"2,260",905,"3,165","2,048",NaN,"789 2,837",780,571,"1,351 234",133 367
4,Akwa Ibom,"1,960","1,477","3,437","1,442",NaN,"1,105 2,547","1,168",786,"1,954 273",227 500

In [ ]:
teachers_16.columns = [
    "state",
    "pub_male",
    "pub_female",
    "pub_total",
    "pub_qualified_male",
    "missing_values",
    "pub_qualified_female_and_total",
    "priv_male",
    "priv_female",
    "priv_total_and_qualified_male",
    "priv_qualified_female_and_total"
]

In [ ]:
teachers_16.head()

,state,pub_male,pub_female,pub_total,pub_qualified_male,missing_values,pub_qualified_female_and_total,priv_male,priv_female,priv_total_and_qualified_male,priv_qualified_female_and_total
0,State,NaN,All Teachers,NaN,NaN,Qualified Teachers,NaN,NaN,All Teachers,Qualified Teachers,NaN
1,NaN,M,F,M+F,M,NaN,F M+F,M,F,M+F M,F M+F
2,Abia,444,"1,209","1,653",380,NaN,"1,003 1,383","1,481","1,953","3,434 377","638 1,015"
3,Adamawa,"2,260",905,"3,165","2,048",NaN,"789 2,837",780,571,"1,351 234",133 367
4,Akwa Ibom,"1,960","1,477","3,437","1,442",NaN,"1,105 2,547","1,168",786,"1,954 273",227 500

In [ ]:
# Splitting the combined columns
teachers_16[["pub_qualified_female", "pub_qualified_total"]] = (
teachers_16["pub_qualified_female_and_total"].str.split(expand=True))

teachers_16[["priv_total", "priv_qualified_male"]] = (
teachers_16["priv_total_and_qualified_male"].str.split(expand=True))

teachers_16[["priv_qualified_female", "priv_qualified_total"]] = (
teachers_16["priv_qualified_female_and_total"].str.split(expand=True))

# Dropping the combined columns
teachers_16 = teachers_16.drop(columns=[
    "pub_qualified_female_and_total",
    "priv_total_and_qualified_male",
    "priv_qualified_female_and_total"
])

In [ ]:
# Viewing the result
teachers_16.head()

,state,pub_male,pub_female,pub_total,pub_qualified_male,missing_values,priv_male,priv_female,pub_qualified_female,pub_qualified_total,priv_total,priv_qualified_male,priv_qualified_female,priv_qualified_total
0,State,NaN,All Teachers,NaN,NaN,Qualified Teachers,NaN,All Teachers,NaN,NaN,Qualified,Teachers,NaN,NaN
1,NaN,M,F,M+F,M,NaN,M,F,F,M+F,M+F,M,F,M+F
2,Abia,444,"1,209","1,653",380,NaN,"1,481","1,953","1,003","1,383","3,434",377,638,"1,015"
3,Adamawa,"2,260",905,"3,165","2,048",NaN,780,571,789,"2,837","1,351",234,133,367
4,Akwa Ibom,"1,960","1,477","3,437","1,442",NaN,"1,168",786,"1,105","2,547","1,954",273,227,500

In [ ]:
# Viewing the order of the columns
teachers_16.columns.tolist()

['state',
 'pub_male',
 'pub_female',
 'pub_total',
 'pub_qualified_male',
 'missing_values',
 'priv_male',
 'priv_female',
 'pub_qualified_female',
 'pub_qualified_total',
 'priv_total',
 'priv_qualified_male',
 'priv_qualified_female',
 'priv_qualified_total']

In [ ]:
# Changing the order of the columns
teachers_16 = teachers_16[
    [
        "state",
        "pub_male",
        "pub_female",
        "pub_total",
        "pub_qualified_male",
        "missing_values",
        "pub_qualified_female",
        "pub_qualified_total",
        "priv_male",
        "priv_female",
        "priv_total",
        "priv_qualified_male",
        "priv_qualified_female",
        "priv_qualified_total"
    ]
]

In [ ]:
# Viewing the result
teachers_16.head()

,state,pub_male,pub_female,pub_total,pub_qualified_male,missing_values,pub_qualified_female,pub_qualified_total,priv_male,priv_female,priv_total,priv_qualified_male,priv_qualified_female,priv_qualified_total
0,State,NaN,All Teachers,NaN,NaN,Qualified Teachers,NaN,NaN,NaN,All Teachers,Qualified,Teachers,NaN,NaN
1,NaN,M,F,M+F,M,NaN,F,M+F,M,F,M+F,M,F,M+F
2,Abia,444,"1,209","1,653",380,NaN,"1,003","1,383","1,481","1,953","3,434",377,638,"1,015"
3,Adamawa,"2,260",905,"3,165","2,048",NaN,789,"2,837",780,571,"1,351",234,133,367
4,Akwa Ibom,"1,960","1,477","3,437","1,442",NaN,"1,105","2,547","1,168",786,"1,954",273,227,500

In [ ]:
# Dropping the first two rows
teachers_16 = teachers_16.iloc[2:].reset_index(drop=True)

In [ ]:
# Viewing the result
teachers_16.head()

,state,pub_male,pub_female,pub_total,pub_qualified_male,missing_values,pub_qualified_female,pub_qualified_total,priv_male,priv_female,priv_total,priv_qualified_male,priv_qualified_female,priv_qualified_total
0,Abia,444,"1,209","1,653",380,NaN,"1,003","1,383","1,481","1,953","3,434",377,638,"1,015"
1,Adamawa,"2,260",905,"3,165","2,048",NaN,789,"2,837",780,571,"1,351",234,133,367
2,Akwa Ibom,"1,960","1,477","3,437","1,442",NaN,"1,105","2,547","1,168",786,"1,954",273,227,500
3,Anambra,"1,102","5,513","6,615","1,000",NaN,"5,056","6,056","1,087","1,007","2,094",526,718,"1,244"
4,Bauchi,"3,584","1,178","4,762","2,812",NaN,"1,023","3,835",466,144,610,255,66,321

In [ ]:
# Dropping the rows with missing values
teachers_16 = teachers_16.dropna(axis=1, how="all")

In [ ]:
# Viewing the result
teachers_16.head()

,state,pub_male,pub_female,pub_total,pub_qualified_male,pub_qualified_female,pub_qualified_total,priv_male,priv_female,priv_total,priv_qualified_male,priv_qualified_female,priv_qualified_total
0,Abia,444,"1,209","1,653",380,"1,003","1,383","1,481","1,953","3,434",377,638,"1,015"
1,Adamawa,"2,260",905,"3,165","2,048",789,"2,837",780,571,"1,351",234,133,367
2,Akwa Ibom,"1,960","1,477","3,437","1,442","1,105","2,547","1,168",786,"1,954",273,227,500
3,Anambra,"1,102","5,513","6,615","1,000","5,056","6,056","1,087","1,007","2,094",526,718,"1,244"
4,Bauchi,"3,584","1,178","4,762","2,812","1,023","3,835",466,144,610,255,66,321

In [ ]:
# Viewing the data types of the columns
teachers_16.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 38 entries, 0 to 37
Data columns (total 13 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   state                  38 non-null     object
 1   pub_male               38 non-null     object
 2   pub_female             38 non-null     object
 3   pub_total              38 non-null     object
 4   pub_qualified_male     38 non-null     object
 5   pub_qualified_female   38 non-null     object
 6   pub_qualified_total    38 non-null     object
 7   priv_male              37 non-null     object
 8   priv_female            37 non-null     object
 9   priv_total             38 non-null     object
 10  priv_qualified_male    38 non-null     object
 11  priv_qualified_female  38 non-null     object
 12  priv_qualified_total   38 non-null     object
dtypes: object(13)
memory usage: 4.0+ KB

In [ ]:
# Converting the numerical columns to their appropriate data type

# Defining the numerical columns
num_cols = [
    "pub_male",
    "pub_female",
    "pub_total",
    "pub_qualified_male",
    "pub_qualified_female",
    "pub_qualified_total",
    "priv_male",
    "priv_female",
    "priv_total",
    "priv_qualified_male",
    "priv_qualified_female",
    "priv_qualified_total"
]

# Converting them
for col in num_cols:
  teachers_16[col] = teachers_16[col].str.replace(",", "", regex=True)
  teachers_16[col] = pd.to_numeric(teachers_16[col], errors="coerce").astype("Int64")

In [ ]:
# Viewing the result
teachers_16.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 38 entries, 0 to 37
Data columns (total 13 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   state                  38 non-null     object
 1   pub_male               38 non-null     Int64
 2   pub_female             38 non-null     Int64
 3   pub_total              38 non-null     Int64
 4   pub_qualified_male     38 non-null     Int64
 5   pub_qualified_female   38 non-null     Int64
 6   pub_qualified_total    38 non-null     Int64
 7   priv_male              37 non-null     Int64
 8   priv_female            37 non-null     Int64
 9   priv_total             37 non-null     Int64
 10  priv_qualified_male    37 non-null     Int64
 11  priv_qualified_female  37 non-null     Int64
 12  priv_qualified_total   37 non-null     Int64
dtypes: Int64(12), object(1)
memory usage: 4.4+ KB

In [ ]:
# Separating the dataframe into public and private dataframes
pub_teachers_16 = teachers_16[
    [
        "state",
        "pub_male",
        "pub_female",
        "pub_total",
        "pub_qualified_male",
        "pub_qualified_female",
        "pub_qualified_total"
    ]
]

priv_teachers_16 = teachers_16[
    [
        "state",
        "priv_male",
        "priv_female",
        "priv_total",
        "priv_qualified_male",
        "priv_qualified_female",
        "priv_qualified_total"
    ]
]

In [ ]:
# Viewing the results
pub_teachers_16.head()

,state,pub_male,pub_female,pub_total,pub_qualified_male,pub_qualified_female,pub_qualified_total
0,Abia,444,1209,1653,380,1003,1383
1,Adamawa,2260,905,3165,2048,789,2837
2,Akwa Ibom,1960,1477,3437,1442,1105,2547
3,Anambra,1102,5513,6615,1000,5056,6056
4,Bauchi,3584,1178,4762,2812,1023,3835

In [ ]:
priv_teachers_16.head()

,state,priv_male,priv_female,priv_total,priv_qualified_male,priv_qualified_female,priv_qualified_total
0,Abia,1481,1953,3434,377,638,1015
1,Adamawa,780,571,1351,234,133,367
2,Akwa Ibom,1168,786,1954,273,227,500
3,Anambra,1087,1007,2094,526,718,1244
4,Bauchi,466,144,610,255,66,321

In [ ]:
# Changing the column names
pub_teachers_16.columns = [
    "state",
    "male",
    "female",
    "total",
    "qualified_male",
    "qualified_female",
    "qualified_total"
]

priv_teachers_16.columns = [
    "state",
    "male",
    "female",
    "total",
    "qualified_male",
    "qualified_female",
    "qualified_total"
]

In [ ]:
# Viewing the results
pub_teachers_16.head()

,state,male,female,total,qualified_male,qualified_female,qualified_total
0,Abia,444,1209,1653,380,1003,1383
1,Adamawa,2260,905,3165,2048,789,2837
2,Akwa Ibom,1960,1477,3437,1442,1105,2547
3,Anambra,1102,5513,6615,1000,5056,6056
4,Bauchi,3584,1178,4762,2812,1023,3835

In [ ]:
priv_teachers_16.head()

,state,male,female,total,qualified_male,qualified_female,qualified_total
0,Abia,1481,1953,3434,377,638,1015
1,Adamawa,780,571,1351,234,133,367
2,Akwa Ibom,1168,786,1954,273,227,500
3,Anambra,1087,1007,2094,526,718,1244
4,Bauchi,466,144,610,255,66,321

In [ ]:
# Converting the dataframes into CSV files
pub_teachers_16.to_csv("Cleaned 2016 Public Teacher Data.csv", index=False)
priv_teachers_16.to_csv("Cleaned 2016 Private Teacher Data.csv", index=False)

# Downloading the CSV files
files.download("Cleaned 2016 Public Teacher Data.csv")
files.download("Cleaned 2016 Private Teacher Data.csv")

# 2017 PUBLIC STUDENT DATA

In [ ]:
pub_student_17 = pd.read_csv("/content/2017 Public Student Data.csv")

In [ ]:
# Viewing the first five rows
pub_student_17.head()

,Unnamed: 0,Unnamed: 1,No. of,SSS 1,Unnamed: 4,Unnamed: 5,SSS 2,Unnamed: 7,Unnamed: 8,SSS 3,Unnamed: 10,Unnamed: 11,Total,Unnamed: 13
0,NaN,State,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,Schools M,F,NaN,M,F,NaN,M,F,NaN,M,F,M+F
2,Abia,NaN,"233 2,163","3,016",NaN,"1,828","2,653",NaN,"1,526","2,165",NaN,"5,517","7,834","13,351"
3,Adamawa*,NaN,"298 12,753","10,028",NaN,"17,246","12,291",NaN,"13,067","10,415",NaN,"43,066","32,734","75,800"
4,Akwa Ibom,NaN,"250 17,344","17,818",NaN,"16,457","16,987",NaN,"12,768","13,070",NaN,"46,569","47,875","94,444"

In [ ]:
# Viewing the last five rows
pub_student_17.tail()

,Unnamed: 0,Unnamed: 1,No. of,SSS 1,Unnamed: 4,Unnamed: 5,SSS 2,Unnamed: 7,Unnamed: 8,SSS 3,Unnamed: 10,Unnamed: 11,Total,Unnamed: 13
38,Zamfara,NaN,"153 15,047","7,810",NaN,"15,996","6,748",NaN,"16,733","6,732",NaN,"7,776","21,290","69,066"
39,NaN,NaN,"675,59",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
40,National,NaN,"9,015","588,645",NaN,"644,623","547,468",NaN,"538,345","429,502",NaN,"1,858,560","1,565,615","3,424,175"
41,NaN,NaN,NaN,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
42,NaN,Note: *=Data imported from 2015/2016,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
# Dropping the last two rows
pub_student_17 = pub_student_17.drop(index=[41, 42])

In [ ]:
# Viewing the result
pub_student_17.tail()

,Unnamed: 0,Unnamed: 1,No. of,SSS 1,Unnamed: 4,Unnamed: 5,SSS 2,Unnamed: 7,Unnamed: 8,SSS 3,Unnamed: 10,Unnamed: 11,Total,Unnamed: 13
36,Taraba,NaN,"210 8,497","6,317",NaN,"6,741","12,149",NaN,"6,585","4,614",NaN,"21,823","23,080","44,903"
37,Yobe,NaN,"48 5,096","2,276",NaN,"5,342","2,175",NaN,"4,453","1,580",NaN,"14,891","6,031","20,922"
38,Zamfara,NaN,"153 15,047","7,810",NaN,"15,996","6,748",NaN,"16,733","6,732",NaN,"7,776","21,290","69,066"
39,NaN,NaN,"675,59",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
40,National,NaN,"9,015","588,645",NaN,"644,623","547,468",NaN,"538,345","429,502",NaN,"1,858,560","1,565,615","3,424,175"

In [ ]:
pub_student_17.head(

)

,Unnamed: 0,Unnamed: 1,No. of,SSS 1,Unnamed: 4,Unnamed: 5,SSS 2,Unnamed: 7,Unnamed: 8,SSS 3,Unnamed: 10,Unnamed: 11,Total,Unnamed: 13
0,NaN,State,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,Schools M,F,NaN,M,F,NaN,M,F,NaN,M,F,M+F
2,Abia,NaN,"233 2,163","3,016",NaN,"1,828","2,653",NaN,"1,526","2,165",NaN,"5,517","7,834","13,351"
3,Adamawa*,NaN,"298 12,753","10,028",NaN,"17,246","12,291",NaN,"13,067","10,415",NaN,"43,066","32,734","75,800"
4,Akwa Ibom,NaN,"250 17,344","17,818",NaN,"16,457","16,987",NaN,"12,768","13,070",NaN,"46,569","47,875","94,444"

In [ ]:
pub_student_17.columns = [
    "state",
    "missing_values_1",
    "num_schools_and_ss1_male",
    "ss1_female",
    "missing_values_2",
    "ss2_male",
    "ss2_female",
    "missing_values_3",
    "ss3_male",
    "ss3_female",
    "missing_values_4",
    "total_male",
    "total_female",
    "total_male_and_female"
]

In [ ]:
# Viewing the result
pub_student_17.head()

,state,missing_values_1,num_schools_and_ss1_male,ss1_female,missing_values_2,ss2_male,ss2_female,missing_values_3,ss3_male,ss3_female,missing_values_4,total_male,total_female,total_male_and_female
0,NaN,State,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,Schools M,F,NaN,M,F,NaN,M,F,NaN,M,F,M+F
2,Abia,NaN,"233 2,163","3,016",NaN,"1,828","2,653",NaN,"1,526","2,165",NaN,"5,517","7,834","13,351"
3,Adamawa*,NaN,"298 12,753","10,028",NaN,"17,246","12,291",NaN,"13,067","10,415",NaN,"43,066","32,734","75,800"
4,Akwa Ibom,NaN,"250 17,344","17,818",NaN,"16,457","16,987",NaN,"12,768","13,070",NaN,"46,569","47,875","94,444"

In [ ]:
# Dropping the first two columns
pub_student_17 = pub_student_17.drop(index=[0, 1]).reset_index(drop=True)

In [ ]:
# Viewing the result
pub_student_17.head()

,state,missing_values_1,num_schools_and_ss1_male,ss1_female,missing_values_2,ss2_male,ss2_female,missing_values_3,ss3_male,ss3_female,missing_values_4,total_male,total_female,total_male_and_female
0,Abia,NaN,"233 2,163","3,016",NaN,"1,828","2,653",NaN,"1,526","2,165",NaN,"5,517","7,834","13,351"
1,Adamawa*,NaN,"298 12,753","10,028",NaN,"17,246","12,291",NaN,"13,067","10,415",NaN,"43,066","32,734","75,800"
2,Akwa Ibom,NaN,"250 17,344","17,818",NaN,"16,457","16,987",NaN,"12,768","13,070",NaN,"46,569","47,875","94,444"
3,Anambra,NaN,"257 8,506","10,196",NaN,"8,330","10,549",NaN,"6,209","8,510",NaN,"23,045","29,255","52,300"
4,Bauchi,NaN,"190 21,597","13,212",NaN,"22,464","12,378",NaN,"20,741","10,393",NaN,"64,802","35,983","100,785"

In [ ]:
# Dropping the columns with missing values
pub_student_17 = pub_student_17.dropna(axis=1, how="all")

In [ ]:
# Viewing the result
pub_student_17.head()

,state,num_schools_and_ss1_male,ss1_female,ss2_male,ss2_female,ss3_male,ss3_female,total_male,total_female,total_male_and_female
0,Abia,"233 2,163","3,016","1,828","2,653","1,526","2,165","5,517","7,834","13,351"
1,Adamawa*,"298 12,753","10,028","17,246","12,291","13,067","10,415","43,066","32,734","75,800"
2,Akwa Ibom,"250 17,344","17,818","16,457","16,987","12,768","13,070","46,569","47,875","94,444"
3,Anambra,"257 8,506","10,196","8,330","10,549","6,209","8,510","23,045","29,255","52,300"
4,Bauchi,"190 21,597","13,212","22,464","12,378","20,741","10,393","64,802","35,983","100,785"

In [ ]:
pub_student_17.columns.tolist()

['state',
 'num_schools_and_ss1_male',
 'ss1_female',
 'ss2_male',
 'ss2_female',
 'ss3_male',
 'ss3_female',
 'total_male',
 'total_female',
 'total_male_and_female']

In [ ]:
# Separating the aggregated column
pub_student_17[["num_schools", "ss1_male"]] = (
pub_student_17["num_schools_and_ss1_male"].str.split(expand=True)
)

# Dropping the aggregated column
pub_student_17 = pub_student_17.drop(columns="num_schools_and_ss1_male")

In [ ]:
# Viewing the result
pub_student_17.head()

,state,ss1_female,ss2_male,ss2_female,ss3_male,ss3_female,total_male,total_female,total_male_and_female,num_schools,ss1_male
0,Abia,"3,016","1,828","2,653","1,526","2,165","5,517","7,834","13,351",233,"2,163"
1,Adamawa*,"10,028","17,246","12,291","13,067","10,415","43,066","32,734","75,800",298,"12,753"
2,Akwa Ibom,"17,818","16,457","16,987","12,768","13,070","46,569","47,875","94,444",250,"17,344"
3,Anambra,"10,196","8,330","10,549","6,209","8,510","23,045","29,255","52,300",257,"8,506"
4,Bauchi,"13,212","22,464","12,378","20,741","10,393","64,802","35,983","100,785",190,"21,597"

In [ ]:
# Reordering the columns
pub_student_17 = pub_student_17[[
    "state",
    "num_schools",
    "ss1_male",
    "ss1_female",
    "ss2_male",
    "ss2_female",
    "ss3_male",
    "ss3_female",
    "total_male",
    "total_female",
    "total_male_and_female"
]]

In [ ]:
# Viewing the result
pub_student_17.head()

,state,num_schools,ss1_male,ss1_female,ss2_male,ss2_female,ss3_male,ss3_female,total_male,total_female,total_male_and_female
0,Abia,233,"2,163","3,016","1,828","2,653","1,526","2,165","5,517","7,834","13,351"
1,Adamawa*,298,"12,753","10,028","17,246","12,291","13,067","10,415","43,066","32,734","75,800"
2,Akwa Ibom,250,"17,344","17,818","16,457","16,987","12,768","13,070","46,569","47,875","94,444"
3,Anambra,257,"8,506","10,196","8,330","10,549","6,209","8,510","23,045","29,255","52,300"
4,Bauchi,190,"21,597","13,212","22,464","12,378","20,741","10,393","64,802","35,983","100,785"

In [ ]:
# Viewing the data types of the dataframe
pub_student_17.dtypes

state                    object
num_schools              object
ss1_male                 object
ss1_female               object
ss2_male                 object
ss2_female               object
ss3_male                 object
ss3_female               object
total_male               object
total_female             object
total_male_and_female    object
dtype: object

In [ ]:
# Converting the numerical columns

# Defining them
num_cols = [
    "num_schools",
    "ss1_male",
    "ss1_female",
    "ss2_male",
    "ss2_female",
    "ss3_male",
    "ss3_female",
    "total_male",
    "total_female",
    "total_male_and_female"
]

# Converting them
for col in num_cols:
  pub_student_17[col] = pub_student_17[col].str.replace(",", "", regex=False)
  pub_student_17[col] = pd.to_numeric(pub_student_17[col]).astype("Int64")

In [ ]:
# Viewing the result
pub_student_17.dtypes

state                    object
num_schools               Int64
ss1_male                  Int64
ss1_female                Int64
ss2_male                  Int64
ss2_female                Int64
ss3_male                  Int64
ss3_female                Int64
total_male                Int64
total_female              Int64
total_male_and_female     Int64
dtype: object

In [ ]:
pub_student_17.tail()

,state,num_schools,ss1_male,ss1_female,ss2_male,ss2_female,ss3_male,ss3_female,total_male,total_female,total_male_and_female
34,Taraba,210,8497,6317,6741,12149,6585,4614,21823,23080,44903
35,Yobe,48,5096,2276,5342,2175,4453,1580,14891,6031,20922
36,Zamfara,153,15047,7810,15996,6748,16733,6732,7776,21290,69066
37,NaN,67559,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
38,National,9015,<NA>,588645,644623,547468,538345,429502,1858560,1565615,3424175

In [ ]:
# Dropping the 37th row
pub_student_17 = pub_student_17.drop(index=37).reset_index(drop=True)

In [ ]:
pub_student_17.tail()

,state,num_schools,ss1_male,ss1_female,ss2_male,ss2_female,ss3_male,ss3_female,total_male,total_female,total_male_and_female
33,Sokoto,111,16026,7704,18149,9038,18040,7891,52215,24633,76848
34,Taraba,210,8497,6317,6741,12149,6585,4614,21823,23080,44903
35,Yobe,48,5096,2276,5342,2175,4453,1580,14891,6031,20922
36,Zamfara,153,15047,7810,15996,6748,16733,6732,7776,21290,69066
37,National,9015,<NA>,588645,644623,547468,538345,429502,1858560,1565615,3424175

In [ ]:
pub_student_17.isna().sum()

state                    0
num_schools              0
ss1_male                 1
ss1_female               0
ss2_male                 0
ss2_female               0
ss3_male                 0
ss3_female               0
total_male               0
total_female             0
total_male_and_female    0
dtype: int64

In [ ]:
pub_student_17.loc[(pub_student_17["state"] == "National"), "ss1_male"] = 67559

In [ ]:
pub_student_17.tail()

,state,num_schools,ss1_male,ss1_female,ss2_male,ss2_female,ss3_male,ss3_female,total_male,total_female,total_male_and_female
33,Sokoto,111,16026,7704,18149,9038,18040,7891,52215,24633,76848
34,Taraba,210,8497,6317,6741,12149,6585,4614,21823,23080,44903
35,Yobe,48,5096,2276,5342,2175,4453,1580,14891,6031,20922
36,Zamfara,153,15047,7810,15996,6748,16733,6732,7776,21290,69066
37,National,9015,67559,588645,644623,547468,538345,429502,1858560,1565615,3424175

In [ ]:
# Converting the dataframe to a CSV file
pub_student_17.to_csv("Cleaned 2017 Public Student Data.csv", index=False)

files.download("Cleaned 2017 Public Student Data.csv")

# 2017 PRIVATE STUDENT DATA

In [ ]:
# Loading the dataframe
priv_students_17 = pd.read_csv("/content/2017 Private Student Data.csv")

In [ ]:
# Viewing the first five rows of the dataframe
priv_students_17.head()

,Unnamed: 0,No. of,SSS 1,Unnamed: 3,Unnamed: 4,SSS 2,Unnamed: 6,SSS 3,Unnamed: 8,Total
0,State,School,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,M,F,NaN,M,F,M,F,M,F M+F
2,NaN,s,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Abia,"1,095 7,136","7,608",NaN,"6,531","6,298","5,593","6,114","19,260","20,020 39,280"
4,Adamawa*,96 989,884,NaN,845,802,646,579,"2,480","2,265 4,745"

In [ ]:
# Renaming the columns
priv_students_17.columns = [
    "state",
    "num_schools_and_ss1_male",
    "ss1_female",
    "missing_values",
    "ss2_male",
    "ss2_female",
    "ss3_male",
    "ss3_female",
    "total_male",
    "total_female_and_students"
]

In [ ]:
# Viewing the result
priv_students_17.head()

,state,num_schools_and_ss1_male,ss1_female,missing_values,ss2_male,ss2_female,ss3_male,ss3_female,total_male,total_female_and_students
0,State,School,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,M,F,NaN,M,F,M,F,M,F M+F
2,NaN,s,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Abia,"1,095 7,136","7,608",NaN,"6,531","6,298","5,593","6,114","19,260","20,020 39,280"
4,Adamawa*,96 989,884,NaN,845,802,646,579,"2,480","2,265 4,745"

In [ ]:
# Viewing the result (contd.)
priv_students_17.tail()

,state,num_schools_and_ss1_male,ss1_female,missing_values,ss2_male,ss2_female,ss3_male,ss3_female,total_male,total_female_and_students
37,Taraba,"216 4,546","3,919",NaN,"3,786","3,220","3,494","2,924","11,826","10,063 21,889"
38,Yobe,"87 1,743","1,560",NaN,"2,259","2,555","1,997","2,105","5,999","6,220 12,219"
39,Zamfara,"82 2,079","1,864",NaN,"1,476","1,317","1,104",977,"4,659","4,158 8,817"
40,National,"13,423 157,957","161,739","148,161",NaN,"152,111","137,851","141,353","443,969","455,203 899,172"
41,Note: *=Data imported from 2015/2016,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
# Dropping the rows at index 0, 1, 2, and 41
priv_students_17 = priv_students_17.drop(index=[0, 1, 2, 41]).reset_index(drop=True)

In [ ]:
# Viewing the result
priv_students_17.head()

,state,num_schools_and_ss1_male,ss1_female,missing_values,ss2_male,ss2_female,ss3_male,ss3_female,total_male,total_female_and_students
0,Abia,"1,095 7,136","7,608",NaN,"6,531","6,298","5,593","6,114","19,260","20,020 39,280"
1,Adamawa*,96 989,884,NaN,845,802,646,579,"2,480","2,265 4,745"
2,Akwa Ibom,"488 3,614","3,904",NaN,"4,134","4,502","4,049","4,287","11,797","12,693 24,490"
3,Anambra,"556 1,094","1,008",NaN,"1,134","1,008","1,113","1,155","3,341","3,171 6,512"
4,Bauchi,"215 5,438","5,959",NaN,"4,715","5,273","4,675","4,956","14,828","16,188 31,016"

In [ ]:
# Viewign the result (contd.)
priv_students_17.tail()

,state,num_schools_and_ss1_male,ss1_female,missing_values,ss2_male,ss2_female,ss3_male,ss3_female,total_male,total_female_and_students
33,Sokoto,42 971,981,NaN,848,783,554,607,"2,373","2,371 4,744"
34,Taraba,"216 4,546","3,919",NaN,"3,786","3,220","3,494","2,924","11,826","10,063 21,889"
35,Yobe,"87 1,743","1,560",NaN,"2,259","2,555","1,997","2,105","5,999","6,220 12,219"
36,Zamfara,"82 2,079","1,864",NaN,"1,476","1,317","1,104",977,"4,659","4,158 8,817"
37,National,"13,423 157,957","161,739","148,161",NaN,"152,111","137,851","141,353","443,969","455,203 899,172"

In [ ]:
# Dropping the column filled with missing values
priv_students_17 = priv_students_17.dropna(axis=1, how="all")

In [ ]:
# Viewing the result
priv_students_17.head()

,state,num_schools_and_ss1_male,ss1_female,missing_values,ss2_male,ss2_female,ss3_male,ss3_female,total_male,total_female_and_students
0,Abia,"1,095 7,136","7,608",NaN,"6,531","6,298","5,593","6,114","19,260","20,020 39,280"
1,Adamawa*,96 989,884,NaN,845,802,646,579,"2,480","2,265 4,745"
2,Akwa Ibom,"488 3,614","3,904",NaN,"4,134","4,502","4,049","4,287","11,797","12,693 24,490"
3,Anambra,"556 1,094","1,008",NaN,"1,134","1,008","1,113","1,155","3,341","3,171 6,512"
4,Bauchi,"215 5,438","5,959",NaN,"4,715","5,273","4,675","4,956","14,828","16,188 31,016"

In [ ]:
priv_students_17

,state,num_schools_and_ss1_male,ss1_female,missing_values,ss2_male,ss2_female,ss3_male,ss3_female,total_male,total_female_and_students
0,Abia,"1,095 7,136","7,608",NaN,"6,531","6,298","5,593","6,114","19,260","20,020 39,280"
1,Adamawa*,96 989,884,NaN,845,802,646,579,"2,480","2,265 4,745"
2,Akwa Ibom,"488 3,614","3,904",NaN,"4,134","4,502","4,049","4,287","11,797","12,693 24,490"
3,Anambra,"556 1,094","1,008",NaN,"1,134","1,008","1,113","1,155","3,341","3,171 6,512"
4,Bauchi,"215 5,438","5,959",NaN,"4,715","5,273","4,675","4,956","14,828","16,188 31,016"
5,Bayelsa,93 776,781,NaN,505,592,199,315,"1,480","1,688 3,168"
6,Benue,"1,174 8,046","8,085",NaN,"7,226","6,505","6,431","5,559","21,703","20,149 41,852"
7,Borno*,26 915,909,NaN,"1,093",994,716,601,"2,724","2,504 5,228"
8,Cross River,"111 1,606","1,845",NaN,"1,523","1,615","1,739","1,898","4,868","5,358 10,226"
9,Delta,"299 4,077","4,227",NaN,"3,829","4,050","3,713","3,723","11,619","12,000 23,619"
10,Ebonyi,"133 3,322","3,622",NaN,"3,149","3,519","3,088","3,221","9,559","10,362 19,921"
11,Edo,"312 4,576","4,681",NaN,"4,068","4,344","4,476","4,611","13,120","13,636 26,756"
12,Ekiti,"678 1,107","1,133",NaN,"1,292","1,508","1,273","1,288","3,672","3,929 7,601"
13,Enugu,"288 6,343","7,241",NaN,"6,496","7,257","6,555","7,689","19,394","22,187 41,581"
14,FCT,"202 1,411","1,516",NaN,"1,414","1,538","1,135","1,318","3,960","4,372 8,332"
15,Gombe,"149 4,548","3,658",NaN,"4,449","3,604","3,868","3,345","12,865","10,607 23,472"
16,Imo*,193 386,405,NaN,339,374,330,379,"1,055","1,158 2,213"
17,Jigawa,11 175,210,NaN,179,172,115,142,469,524 993
18,Kaduna,"462 7,791","7,969",NaN,"6,745","6,431","5,643","5,503","20,179","19,903 40,082"
19,Kano,"396 7,637","9,008",NaN,"5,647","6,956","4,487","5,761","17,771","21,725 39,496"
20,Katsina,"100 3,496","2,961",NaN,"2,992","2,364","3,027","1,981","9,515","7,306 16,821"
21,Kebbi,"52 1,282","1,004",NaN,"1,070",794,689,541,"3,041","2,339 5,380"
22,Kogi,"287 3,537","3,762",NaN,"3,144","3,455","2,837","3,011","9,518","10,228 19,746"
23,Kwara,"186 2,807","2,673",NaN,"2,397","2,271","2,099","1,960","7,303","6,904 14,207"
24,Lagos,"2,577 25,320","26,373","24,926",NaN,"26,583","24,401","25,026","74,647","77,982 152,629"
25,Nasarawa,"131 1,867","2,191",NaN,"1,614","1,558","1,324","1,209","4,805","4,958 9,763"
26,Niger,"222 3,649","3,529",NaN,"2,942","2,887","2,517","2,323","9,108","8,739 17,847"
27,Ogun,"868 13,816","13,625","14,532",NaN,"15,427","15,489","16,792","43,837","45,844 89,681"
28,Ondo,"108 1,626","1,712",NaN,"1,648","1,669","1,782","1,629","5,056","5,010 10,066"
29,Osun*,"124 1,210","1,226",NaN,"1,293","1,353","1,068","1,196","3,571","3,775 7,346"
30,Oyo,"690 9,821","10,198",NaN,"9,861","10,138","8,477","9,220","28,159","29,556 57,715"
31,Plateau,"300 5,207","5,227",NaN,"4,473","4,407","3,920","3,814","13,600","13,448 27,048"
32,Rivers,"374 3,993","4,281",NaN,"3,587","3,988","3,228","3,594","10,808","11,863 22,671"
33,Sokoto,42 971,981,NaN,848,783,554,607,"2,373","2,371 4,744"
34,Taraba,"216 4,546","3,919",NaN,"3,786","3,220","3,494","2,924","11,826","10,063 21,889"
35,Yobe,"87 1,743","1,560",NaN,"2,259","2,555","1,997","2,105","5,999","6,220 12,219"
36,Zamfara,"82 2,079","1,864",NaN,"1,476","1,317","1,104",977,"4,659","4,158 8,817"
37,National,"13,423 157,957","161,739","148,161",NaN,"152,111","137,851","141,353","443,969","455,203 899,172"

In [ ]:
# Replacing the 'ss2_male' values for Lagos, Osun, and National
jumbled_states = ["Lagos", "Ogun", "National"]

for state in jumbled_states:
  mask = priv_students_17["state"] == state

  priv_students_17.loc[mask, "ss2_male"] = (
      priv_students_17.loc[mask, "missing_values"]
  )
  priv_students_17.loc[mask, "missing_values"] = np.nan

In [ ]:
# Viewing the result
priv_students_17

,state,num_schools_and_ss1_male,ss1_female,missing_values,ss2_male,ss2_female,ss3_male,ss3_female,total_male,total_female_and_students
0,Abia,"1,095 7,136","7,608",NaN,"6,531","6,298","5,593","6,114","19,260","20,020 39,280"
1,Adamawa*,96 989,884,NaN,845,802,646,579,"2,480","2,265 4,745"
2,Akwa Ibom,"488 3,614","3,904",NaN,"4,134","4,502","4,049","4,287","11,797","12,693 24,490"
3,Anambra,"556 1,094","1,008",NaN,"1,134","1,008","1,113","1,155","3,341","3,171 6,512"
4,Bauchi,"215 5,438","5,959",NaN,"4,715","5,273","4,675","4,956","14,828","16,188 31,016"
5,Bayelsa,93 776,781,NaN,505,592,199,315,"1,480","1,688 3,168"
6,Benue,"1,174 8,046","8,085",NaN,"7,226","6,505","6,431","5,559","21,703","20,149 41,852"
7,Borno*,26 915,909,NaN,"1,093",994,716,601,"2,724","2,504 5,228"
8,Cross River,"111 1,606","1,845",NaN,"1,523","1,615","1,739","1,898","4,868","5,358 10,226"
9,Delta,"299 4,077","4,227",NaN,"3,829","4,050","3,713","3,723","11,619","12,000 23,619"
10,Ebonyi,"133 3,322","3,622",NaN,"3,149","3,519","3,088","3,221","9,559","10,362 19,921"
11,Edo,"312 4,576","4,681",NaN,"4,068","4,344","4,476","4,611","13,120","13,636 26,756"
12,Ekiti,"678 1,107","1,133",NaN,"1,292","1,508","1,273","1,288","3,672","3,929 7,601"
13,Enugu,"288 6,343","7,241",NaN,"6,496","7,257","6,555","7,689","19,394","22,187 41,581"
14,FCT,"202 1,411","1,516",NaN,"1,414","1,538","1,135","1,318","3,960","4,372 8,332"
15,Gombe,"149 4,548","3,658",NaN,"4,449","3,604","3,868","3,345","12,865","10,607 23,472"
16,Imo*,193 386,405,NaN,339,374,330,379,"1,055","1,158 2,213"
17,Jigawa,11 175,210,NaN,179,172,115,142,469,524 993
18,Kaduna,"462 7,791","7,969",NaN,"6,745","6,431","5,643","5,503","20,179","19,903 40,082"
19,Kano,"396 7,637","9,008",NaN,"5,647","6,956","4,487","5,761","17,771","21,725 39,496"
20,Katsina,"100 3,496","2,961",NaN,"2,992","2,364","3,027","1,981","9,515","7,306 16,821"
21,Kebbi,"52 1,282","1,004",NaN,"1,070",794,689,541,"3,041","2,339 5,380"
22,Kogi,"287 3,537","3,762",NaN,"3,144","3,455","2,837","3,011","9,518","10,228 19,746"
23,Kwara,"186 2,807","2,673",NaN,"2,397","2,271","2,099","1,960","7,303","6,904 14,207"
24,Lagos,"2,577 25,320","26,373",NaN,"24,926","26,583","24,401","25,026","74,647","77,982 152,629"
25,Nasarawa,"131 1,867","2,191",NaN,"1,614","1,558","1,324","1,209","4,805","4,958 9,763"
26,Niger,"222 3,649","3,529",NaN,"2,942","2,887","2,517","2,323","9,108","8,739 17,847"
27,Ogun,"868 13,816","13,625",NaN,"14,532","15,427","15,489","16,792","43,837","45,844 89,681"
28,Ondo,"108 1,626","1,712",NaN,"1,648","1,669","1,782","1,629","5,056","5,010 10,066"
29,Osun*,"124 1,210","1,226",NaN,"1,293","1,353","1,068","1,196","3,571","3,775 7,346"
30,Oyo,"690 9,821","10,198",NaN,"9,861","10,138","8,477","9,220","28,159","29,556 57,715"
31,Plateau,"300 5,207","5,227",NaN,"4,473","4,407","3,920","3,814","13,600","13,448 27,048"
32,Rivers,"374 3,993","4,281",NaN,"3,587","3,988","3,228","3,594","10,808","11,863 22,671"
33,Sokoto,42 971,981,NaN,848,783,554,607,"2,373","2,371 4,744"
34,Taraba,"216 4,546","3,919",NaN,"3,786","3,220","3,494","2,924","11,826","10,063 21,889"
35,Yobe,"87 1,743","1,560",NaN,"2,259","2,555","1,997","2,105","5,999","6,220 12,219"
36,Zamfara,"82 2,079","1,864",NaN,"1,476","1,317","1,104",977,"4,659","4,158 8,817"
37,National,"13,423 157,957","161,739",NaN,"148,161","152,111","137,851","141,353","443,969","455,203 899,172"

In [ ]:
# Dropping the column filled with missing values
priv_students_17 = priv_students_17.dropna(axis=1, how="all")

In [ ]:
# Viewing the result
priv_students_17.head()

,state,num_schools_and_ss1_male,ss1_female,ss2_male,ss2_female,ss3_male,ss3_female,total_male,total_female_and_students
0,Abia,"1,095 7,136","7,608","6,531","6,298","5,593","6,114","19,260","20,020 39,280"
1,Adamawa*,96 989,884,845,802,646,579,"2,480","2,265 4,745"
2,Akwa Ibom,"488 3,614","3,904","4,134","4,502","4,049","4,287","11,797","12,693 24,490"
3,Anambra,"556 1,094","1,008","1,134","1,008","1,113","1,155","3,341","3,171 6,512"
4,Bauchi,"215 5,438","5,959","4,715","5,273","4,675","4,956","14,828","16,188 31,016"

In [ ]:
# Separating the aggregated columns
priv_students_17[["num_schools", "ss1_male"]] = (
    priv_students_17['num_schools_and_ss1_male']
    .str
    .split(expand=True)
)
priv_students_17[["total_female", "total_students"]] = (
    priv_students_17["total_female_and_students"]
    .str
    .split(expand=True)
)

# Dropping the aggregated columns
priv_students_17 = (
    priv_students_17.drop(
        columns=["num_schools_and_ss1_male", "total_female_and_students"]
    )
)

In [ ]:
# Viewing the result
priv_students_17.head()

,state,ss1_female,ss2_male,ss2_female,ss3_male,ss3_female,total_male,num_schools,ss1_male,total_female,total_students
0,Abia,"7,608","6,531","6,298","5,593","6,114","19,260","1,095","7,136","20,020","39,280"
1,Adamawa*,884,845,802,646,579,"2,480",96,989,"2,265","4,745"
2,Akwa Ibom,"3,904","4,134","4,502","4,049","4,287","11,797",488,"3,614","12,693","24,490"
3,Anambra,"1,008","1,134","1,008","1,113","1,155","3,341",556,"1,094","3,171","6,512"
4,Bauchi,"5,959","4,715","5,273","4,675","4,956","14,828",215,"5,438","16,188","31,016"

In [ ]:
# Reordering the columns
priv_students_17 = (
    priv_students_17[[
    "state",
    "num_schools",
    "ss1_male",
    "ss1_female",
    "ss2_male",
    "ss2_female",
    "ss3_male",
    "ss3_female",
    "total_male",
    "total_female",
    "total_students"
  ]]
)

In [ ]:
# Viewing the result
priv_students_17.head()

,state,num_schools,ss1_male,ss1_female,ss2_male,ss2_female,ss3_male,ss3_female,total_male,total_female,total_students
0,Abia,"1,095","7,136","7,608","6,531","6,298","5,593","6,114","19,260","20,020","39,280"
1,Adamawa*,96,989,884,845,802,646,579,"2,480","2,265","4,745"
2,Akwa Ibom,488,"3,614","3,904","4,134","4,502","4,049","4,287","11,797","12,693","24,490"
3,Anambra,556,"1,094","1,008","1,134","1,008","1,113","1,155","3,341","3,171","6,512"
4,Bauchi,215,"5,438","5,959","4,715","5,273","4,675","4,956","14,828","16,188","31,016"

In [ ]:
# Viewing the data types of the columns
priv_students_17.dtypes

state             object
num_schools       object
ss1_male          object
ss1_female        object
ss2_male          object
ss2_female        object
ss3_male          object
ss3_female        object
total_male        object
total_female      object
total_students    object
dtype: object

In [ ]:
# Converting the numerical columns
num_cols = [
  "num_schools",
  "ss1_male",
  "ss1_female",
  "ss2_male",
  "ss2_female",
  "ss3_male",
  "ss3_female",
  "total_male",
  "total_female",
  "total_students"
]

# Removing the commas in the numerical columns
for col in num_cols:
  priv_students_17[col] = (
      priv_students_17[col]
      .str
      .replace(",", "", regex=False)
  )

  # Converting them from categorical to numerical columns
  priv_students_17[col] = (
      pd.to_numeric(priv_students_17[col]).astype("Int64")
  )

In [ ]:
# Viewing the result
priv_students_17.dtypes

state             object
num_schools        Int64
ss1_male           Int64
ss1_female         Int64
ss2_male           Int64
ss2_female         Int64
ss3_male           Int64
ss3_female         Int64
total_male         Int64
total_female       Int64
total_students     Int64
dtype: object

In [ ]:
# Converting the result to a CSV and downloading it
file_name = "Cleaned 2017 Private Student Data.csv"

priv_students_17.to_csv(file_name, index=False)
files.download(file_name)

# **2019 Classroom Data**

In [ ]:
# Loading the dataset
classroom_data_19 = pd.read_csv("/content/2019 Classroom Data.csv")

In [ ]:
# Viewing the first ten rows
classroom_data_19.head(10)

,Unnamed: 0,Unnamed: 1,PUBLIC,Unnamed: 3,Unnamed: 4,PRIVATE,Unnamed: 6,PUBLIC + PRIVATE
0,State,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,Good,Bad,Total,Good,Bad,Total,Good Bad Total
2,Abia,583,423,1006,1390,174,1564,1973 597 2570
3,Adamawa,1836,497,2333,1169,152,1321,3005 649 3654
4,Akwa-Ibom,2825,1701,4526,1457,324,1781,4282 2025 6307
5,Anambra,3062,184,3246,1111,20,1131,4173 204 4377
6,Bauchi,2334,34,2368,1132,566,1698,3466 600 4066
7,Bayelsa,996,86,1082,228,30,258,1224 116 1340
8,Benue,1052,96,1148,2255,127,2382,3307 223 3530
9,Borno,NaN,NaN,NaN,NaN,NaN,NaN,NA NA NA

In [ ]:
# Viewing the last ten rows
classroom_data_19.tail(10)

,Unnamed: 0,Unnamed: 1,PUBLIC,Unnamed: 3,Unnamed: 4,PRIVATE,Unnamed: 6,PUBLIC + PRIVATE
30,Ondo,1225,1370,2595,3052,316,3368,4277 1686 5963
31,Osun,NaN,NaN,NaN,NaN,NaN,NaN,NA NA NA
32,Oyo,1211,3716,4927,NaN,NaN,NaN,1211 3716 4927
33,Plateau,1734,638,2372,1740,600,2340,3474 1238 4712
34,Rivers,819,827,1646,6623,0,6623,7442 827 8269
35,Sokoto,1129,314,1443,155,18,173,1284 332 1616
36,Taraba,1274,26,1300,NaN,NaN,NaN,1274 26 1300
37,Yobe,831,119,950,796,221,1017,1627 340 1967
38,Zamfara,399,42,441,571,11,582,970 53 1023
39,National,60460,23269,83729,106196,8154,114350,166656 31423 198079

In [ ]:
# Checking the number of rows and columns
classroom_data_19.shape

(40, 8)

In [ ]:
# Renaming the columns
classroom_data_19.columns = [
    "state",
    "pub_good_classrooms",
    "pub_bad_classrooms",
    "pub_total_classrooms",
    "priv_good_classrooms",
    "priv_bad_classrooms",
    "priv_total_classrooms",
    "total_good_classrooms_and_bad_classrooms_and_classrooms"
]

In [ ]:
classroom_data_19.head()

,state,pub_good_classrooms,pub_bad_classrooms,pub_total_classrooms,priv_good_classrooms,priv_bad_classrooms,priv_total_classrooms,total_good_classrooms_and_bad_classrooms_and_classrooms
0,State,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,Good,Bad,Total,Good,Bad,Total,Good Bad Total
2,Abia,583,423,1006,1390,174,1564,1973 597 2570
3,Adamawa,1836,497,2333,1169,152,1321,3005 649 3654
4,Akwa-Ibom,2825,1701,4526,1457,324,1781,4282 2025 6307

In [ ]:
# Dropping the  two rows
# Dropping the first two rows
classroom_data_19= classroom_data_19.iloc[2:].reset_index(drop=True)

In [ ]:
classroom_data_19.head()

,state,pub_good_classrooms,pub_bad_classrooms,pub_total_classrooms,priv_good_classrooms,priv_bad_classrooms,priv_total_classrooms,total_good_classrooms_and_bad_classrooms_and_classrooms
0,Abia,583,423,1006,1390,174,1564,1973 597 2570
1,Adamawa,1836,497,2333,1169,152,1321,3005 649 3654
2,Akwa-Ibom,2825,1701,4526,1457,324,1781,4282 2025 6307
3,Anambra,3062,184,3246,1111,20,1131,4173 204 4377
4,Bauchi,2334,34,2368,1132,566,1698,3466 600 4066

In [ ]:
# Separating the combined column
classroom_data_19[["total_good_classrooms", "total_bad_classrooms", "total_classrooms"]] = (
    classroom_data_19["total_good_classrooms_and_bad_classrooms_and_classrooms"]
    .str
    .split(expand=True)
)

# Dropping the combined column
classroom_data_19 = classroom_data_19.drop(columns="total_good_classrooms_and_bad_classrooms_and_classrooms")

,state,pub_good_classrooms,pub_bad_classrooms,pub_total_classrooms,priv_good_classrooms,priv_bad_classrooms,priv_total_classrooms,total_good_classrooms,total_bad_classrooms,total_classrooms
0,Abia,583,423,1006,1390,174,1564,1973,597,2570
1,Adamawa,1836,497,2333,1169,152,1321,3005,649,3654
2,Akwa-Ibom,2825,1701,4526,1457,324,1781,4282,2025,6307
3,Anambra,3062,184,3246,1111,20,1131,4173,204,4377
4,Bauchi,2334,34,2368,1132,566,1698,3466,600,4066
5,Bayelsa,996,86,1082,228,30,258,1224,116,1340
6,Benue,1052,96,1148,2255,127,2382,3307,223,3530
7,Borno,NaN,NaN,NaN,NaN,NaN,NaN,NA,NA,NA
8,Cross River,2648,805,3453,2360,682,3042,5008,1487,6495
9,Delta,4004,2209,6213,1873,65,1938,5877,2274,8151
10,Ebonyi,1575,598,2173,5177,598,5775,6752,1196,7948
11,Edo,451,422,873,1293,1186,2479,1744,1608,3352
12,Ekiti,292,1233,1525,1,21,22,293,1254,1547
13,Enugu,2689,73,2762,3500,423,3923,6189,496,6685
14,FCT,913,364,1277,401,3,404,1314,367,1681
15,Gombe,1439,656,2095,NaN,NaN,NaN,1439,656,2095
16,Imo,6650,1576,8226,2252,315,2567,8902,1891,10793
17,Jigawa,178,1528,1706,NaN,NaN,NaN,178,1528,1706
18,Kaduna,2759,734,3493,34837,1213,36050,37596,1947,39543
19,Kano,2256,23,2279,NaN,NaN,NaN,2256,23,2279
20,Katsina,3058,119,3177,1760,74,1834,4818,193,5011
21,Kebbi,1031,263,1294,107,37,144,1138,300,1438
22,Kogi,1114,950,2064,4,5,9,1118,955,2073
23,Kwara,2389,95,2484,NaN,NaN,NaN,2389,95,2484
24,Lagos,2089,39,2128,23600,200,23800,25689,239,25928
25,Nassarawa,250,59,309,1232,330,1562,1482,389,1871
26,Niger,1790,79,1869,1617,40,1657,3407,119,3526
27,Ogun,1575,1371,2946,4503,403,4906,6078,1774,7852
28,Ondo,1225,1370,2595,3052,316,3368,4277,1686,5963
29,Osun,NaN,NaN,NaN,NaN,NaN,NaN,NA,NA,NA
30,Oyo,1211,3716,4927,NaN,NaN,NaN,1211,3716,4927
31,Plateau,1734,638,2372,1740,600,2340,3474,1238,4712
32,Rivers,819,827,1646,6623,0,6623,7442,827,8269
33,Sokoto,1129,314,1443,155,18,173,1284,332,1616
34,Taraba,1274,26,1300,NaN,NaN,NaN,1274,26,1300
35,Yobe,831,119,950,796,221,1017,1627,340,1967
36,Zamfara,399,42,441,571,11,582,970,53,1023
37,National,60460,23269,83729,106196,8154,114350,166656,31423,198079

In [ ]:
# Viewing the result
classroom_data_19.head()

,state,pub_good_classrooms,pub_bad_classrooms,pub_total_classrooms,priv_good_classrooms,priv_bad_classrooms,priv_total_classrooms,total_good_classrooms,total_bad_classrooms,total_classrooms
0,Abia,583,423,1006,1390,174,1564,1973,597,2570
1,Adamawa,1836,497,2333,1169,152,1321,3005,649,3654
2,Akwa-Ibom,2825,1701,4526,1457,324,1781,4282,2025,6307
3,Anambra,3062,184,3246,1111,20,1131,4173,204,4377
4,Bauchi,2334,34,2368,1132,566,1698,3466,600,4066

In [ ]:
# Viewing info about the dataset
classroom_data_19.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 38 entries, 0 to 37
Data columns (total 10 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   state                  38 non-null     object
 1   pub_good_classrooms    36 non-null     object
 2   pub_bad_classrooms     36 non-null     object
 3   pub_total_classrooms   36 non-null     object
 4   priv_good_classrooms   30 non-null     object
 5   priv_bad_classrooms    30 non-null     object
 6   priv_total_classrooms  30 non-null     object
 7   total_good_classrooms  38 non-null     object
 8   total_bad_classrooms   38 non-null     object
 9   total_classrooms       38 non-null     object
dtypes: object(10)
memory usage: 3.1+ KB

In [ ]:
# Converting the numerical columns
num_cols = [
  "pub_good_classrooms",
  "pub_bad_classrooms",
  "pub_total_classrooms",
  "priv_good_classrooms",
  "priv_bad_classrooms",
  "priv_total_classrooms",
  "total_good_classrooms",
  "total_bad_classrooms",
  "total_classrooms"
]

for col in num_cols:
  classroom_data_19[col] = pd.to_numeric(classroom_data_19[col], errors="coerce").astype("Int64")

In [ ]:
# Viewing the result
classroom_data_19.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 38 entries, 0 to 37
Data columns (total 10 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   state                  38 non-null     object
 1   pub_good_classrooms    36 non-null     Int64
 2   pub_bad_classrooms     36 non-null     Int64
 3   pub_total_classrooms   36 non-null     Int64
 4   priv_good_classrooms   30 non-null     Int64
 5   priv_bad_classrooms    30 non-null     Int64
 6   priv_total_classrooms  30 non-null     Int64
 7   total_good_classrooms  36 non-null     Int64
 8   total_bad_classrooms   36 non-null     Int64
 9   total_classrooms       36 non-null     Int64
dtypes: Int64(9), object(1)
memory usage: 3.4+ KB

In [ ]:
# Viewing the result (contd.)
classroom_data_19

,state,pub_good_classrooms,pub_bad_classrooms,pub_total_classrooms,priv_good_classrooms,priv_bad_classrooms,priv_total_classrooms,total_good_classrooms,total_bad_classrooms,total_classrooms
0,Abia,583,423,1006,1390,174,1564,1973,597,2570
1,Adamawa,1836,497,2333,1169,152,1321,3005,649,3654
2,Akwa-Ibom,2825,1701,4526,1457,324,1781,4282,2025,6307
3,Anambra,3062,184,3246,1111,20,1131,4173,204,4377
4,Bauchi,2334,34,2368,1132,566,1698,3466,600,4066
5,Bayelsa,996,86,1082,228,30,258,1224,116,1340
6,Benue,1052,96,1148,2255,127,2382,3307,223,3530
7,Borno,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
8,Cross River,2648,805,3453,2360,682,3042,5008,1487,6495
9,Delta,4004,2209,6213,1873,65,1938,5877,2274,8151
10,Ebonyi,1575,598,2173,5177,598,5775,6752,1196,7948
11,Edo,451,422,873,1293,1186,2479,1744,1608,3352
12,Ekiti,292,1233,1525,1,21,22,293,1254,1547
13,Enugu,2689,73,2762,3500,423,3923,6189,496,6685
14,FCT,913,364,1277,401,3,404,1314,367,1681
15,Gombe,1439,656,2095,<NA>,<NA>,<NA>,1439,656,2095
16,Imo,6650,1576,8226,2252,315,2567,8902,1891,10793
17,Jigawa,178,1528,1706,<NA>,<NA>,<NA>,178,1528,1706
18,Kaduna,2759,734,3493,34837,1213,36050,37596,1947,39543
19,Kano,2256,23,2279,<NA>,<NA>,<NA>,2256,23,2279
20,Katsina,3058,119,3177,1760,74,1834,4818,193,5011
21,Kebbi,1031,263,1294,107,37,144,1138,300,1438
22,Kogi,1114,950,2064,4,5,9,1118,955,2073
23,Kwara,2389,95,2484,<NA>,<NA>,<NA>,2389,95,2484
24,Lagos,2089,39,2128,23600,200,23800,25689,239,25928
25,Nassarawa,250,59,309,1232,330,1562,1482,389,1871
26,Niger,1790,79,1869,1617,40,1657,3407,119,3526
27,Ogun,1575,1371,2946,4503,403,4906,6078,1774,7852
28,Ondo,1225,1370,2595,3052,316,3368,4277,1686,5963
29,Osun,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
30,Oyo,1211,3716,4927,<NA>,<NA>,<NA>,1211,3716,4927
31,Plateau,1734,638,2372,1740,600,2340,3474,1238,4712
32,Rivers,819,827,1646,6623,0,6623,7442,827,8269
33,Sokoto,1129,314,1443,155,18,173,1284,332,1616
34,Taraba,1274,26,1300,<NA>,<NA>,<NA>,1274,26,1300
35,Yobe,831,119,950,796,221,1017,1627,340,1967
36,Zamfara,399,42,441,571,11,582,970,53,1023
37,National,60460,23269,83729,106196,8154,114350,166656,31423,198079

In [ ]:
# Checking the number of missing values in the dataframe
classroom_data_19.isna().sum()

state                    0
pub_good_classrooms      2
pub_bad_classrooms       2
pub_total_classrooms     2
priv_good_classrooms     8
priv_bad_classrooms      8
priv_total_classrooms    8
total_good_classrooms    2
total_bad_classrooms     2
total_classrooms         2
dtype: int64